### ISSUE TITLE
feature reques: NACK support for udp packet lose

### ISSUE THREAD

**Issue by notedit** [aler9/rtsp-simple-server#1]

**Comment by aler9** [comment]
Hi, thanks for your interest in this project (that was written in about 24 hours some days ago, since i couldn't find a working and standalone RTSP server and i spent days trying to make gst-rtsp-server work with every possible input, and i failed).

NACKs are packets sent from a UDP server to a UDP client to signal some kind of errors, you mean that it would be nice if the server was able to detect packet losses from incoming streams (the ones sent by publishers) and send back NACKs when it happens?

**Comment by notedit** [comment]
yes,   ffmpeg's  rtsp  support nack.

**Comment by midicase** [comment]
The UDP streaming part of the protocol does not support NACK (neither does ffmpeg). Not part of the spec.  If you want re-transmit capability then RTSP is not the protocol.  ARQ style protocols, zixi and SRT offer this.
