### ISSUE TITLE
Support oversized RTP/H264 inside tracks with multiple rtpmaps

### ISSUE THREAD

**Issue by tbnguyen1407** [aler9/rtsp-simple-server#1103]
## Which version are you using?

v0.19.2 - v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Using inputs with big RTP packet size failed.

This is an old problem, which was fixed in v0.18.0.

## Describe how to replicate the issue

1. start the server (protocols: [tcp], not sure if required)
2. proxy a stream with big RTP packet size
3. see error in logs

```
2022/08/19 13:43:27 INF [path path1] [rtsp source] ERR: payload size (32793) greater than maximum allowed (1472)
```

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, since v0.18.0 the server re-encodes H264 tracks with non-standard RTP packet sizes, since these can't be used with the UDP transport protocol.

If you're still encountering this error it means that you're either reading a track that doesn't use H264 or that the server doesn't recognizes that track as H264. Please post server logs with `logLevel: debug`.

**Comment by tbnguyen1407** [comment]
See logs below for v0.20.0. Same stream is working for v0.18.0 to v0.19.1. I think there is a regression in v0.19.2 which failed the H.264 detection for the track (showing Generic).

[rtsp-simple-server-0.20.0.log](https://github.com/aler9/rtsp-simple-server/files/9412093/rtsp-simple-server-0.20.0.log)

**Comment by aler9** [comment]
This is your SDP:

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=KaiSquare Streaming Service
i=AAC/H264 Stream
c=IN IP4 0.0.0.0
a=control:*
t=0 0
a=range:npt=now-
m=video 0 RTP/AVP 96 98
a=rtpmap:96 H264/90000
a=rtpmap:98 MetaData
a=rtcp-mux
a=fmtp:96 packetization-mode=1;profile-level-id=4d002a;sprop-parameter-sets=Z00AKp2oHgCJ+WbgICAgQA==,aO48gA==
a=control:streamid=video0
```

The problem of the video track is that it contains both video (`rtpmap:96 H264/90000`) and metadata (`rtpmap:98 MetaData`). It's not a pure video track and is treated as a generic track. It's impossible to re-encode it since the metadata format is not standard and no one knows how to decode or encode it except the vendor. The vendor should have put metadata in an additional track.

**Comment by tbnguyen1407** [comment]
Hello, sorry to bump this but according to rfc4566, if multiple payload types are specified, first one SHOULD be used by default. Could there be a fix for H264 detection similar to this ClockRate fix?

https://github.com/aler9/gortsplib/commit/32224720214e0958f709e98597689326e17acf20

Theorically:
* H264 detection checks the first payload type number
* oversized RTP packet remuxing skips non-H264 packet types

Thank you.

**Comment by aler9** [comment]
Tracks can now have an arbitrary number of formats/codecs, what is missing is the ability to apply algorithms on single formats, and not on the entire track.

**Comment by aler9** [comment]
Generic tracks with multiple formats are supported since v0.20.2; we now need to split the concept of RTSP channels from the concept of tracks, as RTSP channels can contain multiple tracks.

**Comment by aler9** [comment]
Since v0.21.0, codec-specific algorithms (like H264 resizing) are applied to single formats inside tracks, therefore this issue is fixed.
