### ISSUE TITLE
Saving video streams

### ISSUE THREAD

**Issue by Mirabeau2Code** [aler9/rtsp-simple-server#1127]
## Describe the feature

Is there a possibility to add methods for saving video streams?
(in the gortsplib or in your rtsp-simple-server project)

For example optional:

either the constant flow
either the flow per duration slice (1 file per slice)
either the "cyclic" flow of a determined duration (save the last hour for example)
thank you for the beautiful work done, it helps me to learn Go ;)

**Comment by aler9** [comment]
Hello, regarding rtsp-simple-server, at the moment streams can be saved to disk by using `ffmpeg` as described here:
https://github.com/aler9/rtsp-simple-server#save-streams-to-disk

ffmpeg can be configured in order to create segments with a given duration.

If you're interested in a solution that doesn't involve ffmpeg, you can build a custom server by starting from this example:
https://github.com/aler9/gortsplib/blob/main/examples/server-h264-save-to-disk/main.go
