### ISSUE TITLE
runOnRead not running for HLS readers

### ISSUE THREAD

**Issue by Warr1024** [aler9/rtsp-simple-server#1144]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

`runOnRead` does not appear to run when a user reads the HLS stream.

## Describe how to replicate the issue

1. Configure a runOnRead script for any path.  Using hlsDisable=no, hlsAlwaysRemux=no.
2. Start the server.
3. Publish a stream to the matching path.
4. Read the stream with HLS (using an HTML viewer with hls.js).

## Expected Behavior

- When the user requests an HLS stream, this causes the HLS remuxer to kick off, and ALSO kicks off the runOnRead script.
- When the user stops consuming HLS, the remuxer eventually detects this and shuts down the stream; this should ALSO SIGINT the runOnRead script.

## Observed Behavior

- The runOnRead script never runs when reading HLS, even though the HLS stream plays.
- The runOnRead script *will* run if RTSP/RTMP is used to read the same stream (so it's not a script bug or misconfiguration issue).

## Did you attach the server logs?

no (my deployment is too busy; I would need to setup an isolated test environment; let me know if this is actually needed).

## Did you attach a network dump?

no

**Comment by aler9** [comment]
`runOnRead` can't be run when someone reads the stream with HLS since in HLS there is no concept of "user" or "client": stream is splitted into files and these files are served with a static HTTP server. A server doesn't know if a user has started to read a stream and doesn't if it has stopped reading. It just knows that the user has downloaded a segment. If you want to track usage, embed the HLS stream into a more complex web page.
