### ISSUE TITLE
Feature request: Add creation time to stream.m3u8 (HLS stream)

### ISSUE THREAD

**Issue by giano574** [aler9/rtsp-simple-server#1154]
## Describe the feature

It would be very useful to have the start time at the top of stream.m3u8, so that one can check if it is still the same stream or it is a new one, and what time the frame pts's are relative to when using rpiCamera as source. Preferably it would be the same datetime as the datetime of the first segment so it matches the actual start of the recording. Based on [my findings](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-10#appendix-D.5) it seems like it would be okay to add an EXT-X-PROGRAM-DATE-TIME to the top of the media playlist.

**Comment by aler9** [comment]
Hello, `EXT-X-PROGRAM-DATE-TIME` is already added to every segment and you can already use it to extract the RTC timestamp of frames by doing:

```
segment_program_date_time + frame_pts - first_frame_of_segment_pts
```

There's no need to add it to the playlist header.

PTS can't be used as an absolute time reference since it's limited to 33 bits (26 hours), it can be only used as a relative time reference.
