### ISSUE TITLE
LL-HLS is not working - Validation report suggests must fix issues

### ISSUE THREAD

**Issue by ilterpehlivan** [aler9/rtsp-simple-server#1176]
## Which version are you using?

v0.20

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I try to run LL-HLS as described in ReadMe [section](https://github.com/aler9/rtsp-simple-server#low-latency-variant) by using ffmpeg as source `ffmpeg -re -stream_loop -1 -i high_profile_4_1.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream` . However I cannot open the video in the browser, it spins but never opens. <br>
As recommended I played with the `hlsPartDuration` parameter and still no success <br>
> Note I also checked it in Safari as well as different hls.js versions, still no luck!

Moreover I took the report from Apple's official tool `mediastreamvalidator` which basically validate the HLS stream and generates a report and according to that report (attached) some problems must be fixed

## Describe how to replicate the issue

1. start the server
2. publish with `ffmpeg -re -stream_loop -1 -i high_profile_4_1.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream`
3. open browser(firefox/safari) `https://localhost:8888/mystream`

## Did you attach the server logs?

no

## Did you attach a network dump?

no
[validation_data.html.zip](https://github.com/aler9/rtsp-simple-server/files/9700072/validation_data.html.zip)

**Comment by aler9** [comment]
Hello, the report you posted contains the answer to this issue:

```
6. Illegal change in tag
Variant #1, EXT-X-TARGETDURATION value changed from 7 to 8
Variant #1, CAN-SKIP-UNTIL attribute changed from 42.000000 to 48.000000
```

The file you're using to stream contains IDR frames that are not equally spaced one from the other. The first two IDR frames are 7 secs distant, the following IDR is 8 secs after them. EXT-X-TARGETDURATION is increased in order to account for this change. Unfortunately not everything can be streamed with low-latency HLS. Just re-encode the video with ffmpeg and libx264 or use legacy HLS.

Regarding the other major problems:

```
1. Your EXT-X-STREAM-INF and EXT-X-I-FRAME-STREAM-INF tags MUST always provide the RESOLUTION attribute if the rendition(s) include video

    Multivariant Playlist Stream Definition for All Variants

2. You MUST include the AVERAGE-BANDWIDTH attribute

    Multivariant Playlist Stream Definition for All Variants

3. Each EXT-X-STREAM-INF tag MUST have a FRAME-RATE attribute

    Multivariant Playlist Stream Definition for All Variants
```

This is an enhancement that is being tracked here: #1320

```
5. You MUST provide multiple bit rates of video

    Multivariant Playlist
```

This server doesn't re-encode the video and therefore can't provide multiple bit rates.
