### ISSUE TITLE
RTSP proxy mode

### ISSUE THREAD

**Issue by dragonsongohan** [aler9/rtsp-simple-server#124]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Linux

## Describe the problem

Description
I use forward 180 link rtsp mode, 2 clients connect to and view 180 link forward simultaneously. The program crashed.[
![Screenshot from 2020-11-13 16-59-33](https://user-images.githubusercontent.com/12947223/99060163-35bef900-25d2-11eb-8faa-a25843370da3.png)
](url)

**Comment by aler9** [comment]
Hello,
1. please try this nightly release and let me know if it fixes the issue
[rtsp-simple-server_v0.12.1-4-g00678b7_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540674/rtsp-simple-server_v0.12.1-4-g00678b7_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.12.1-4-g00678b7_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540675/rtsp-simple-server_v0.12.1-4-g00678b7_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540676/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540677/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540678/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.1-4-g00678b7_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5540679/rtsp-simple-server_v0.12.1-4-g00678b7_windows_amd64.zip)

2. if the issue is still here, please provide some additional informations:
    1. does the issue arise immediately or after some time?
    2. who is generating the stream? a camera? which camera?
    3. post the configuration or the environment variables
    4. post the full log

thanks

**Comment by dragonsongohan** [comment]
Thanks for update. 
I'm currently running for 6 days with more than 200 cameras, the program is still working well with the program you update.

**Comment by dragonsongohan** [comment]
> Hello,
> 
> 1. please try this nightly release and let me know if it fixes the issue
>    [rtsp-simple-server_v0.12.1-4-g00678b7_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540674/rtsp-simple-server_v0.12.1-4-g00678b7_darwin_amd64.tar.gz)
>    [rtsp-simple-server_v0.12.1-4-g00678b7_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540675/rtsp-simple-server_v0.12.1-4-g00678b7_linux_amd64.tar.gz)
>    [rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540676/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm6.tar.gz)
>    [rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540677/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm7.tar.gz)
>    [rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5540678/rtsp-simple-server_v0.12.1-4-g00678b7_linux_arm64v8.tar.gz)
>    [rtsp-simple-server_v0.12.1-4-g00678b7_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5540679/rtsp-simple-server_v0.12.1-4-g00678b7_windows_amd64.zip)
> 2. if the issue is still here, please provide some additional informations:
>    
>    1. does the issue arise immediately or after some time?
>    2. who is generating the stream? a camera? which camera?
![Screenshot from 2020-11-24 10-37-19](https://user-images.githubusercontent.com/12947223/100044181-986d8b80-2e41-11eb-9ffd-7e5ab4d677d3.png)

>    3. post the configuration or the environment variables
>    4. post the full log
> 
> thanks

1. Service after running for nearly 7 days, then crash.
2. I'm using rtsp proxy mode, 200 cameras, many different manufacturer (Hick, zahua, Axis...)

**Comment by dragonsongohan** [comment]
@aler9 Can you check for this error

**Comment by aler9** [comment]
Hello, that's quite a stress test :)
Please try with this new nightly release (that is branch "crash"), i've added another check in the point where in crashes, let's see if it's enough.
[rtsp-simple-server_v0.12.1-24-ga7d24a9_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5595745/rtsp-simple-server_v0.12.1-24-ga7d24a9_windows_amd64.zip)
[rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5595748/rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5595750/rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5595751/rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5595752/rtsp-simple-server_v0.12.1-24-ga7d24a9_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.1-24-ga7d24a9_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5595753/rtsp-simple-server_v0.12.1-24-ga7d24a9_darwin_amd64.tar.gz)

**Comment by aler9** [comment]
hello, did the fix solve the issue?
