### ISSUE TITLE
RTSP bandwidth issues with UDP protocol

### ISSUE THREAD

**Issue by windows10luke** [aler9/rtsp-simple-server#125]
## Which version are you using?

v0.12.1 arm64

## Which operating system are you using?

Linux

## Describe the problem

I am using gstreamer with the rtspclientsink plugin with a USB HDMI capture card. This card captures in MJPEG so the bitrate is large around 150Mbits/sec. When there is no HDMI source plugged into this card, it displays a colored test video stream to show that it is working. This creates a 15Mbit/sec video stream. I then use the following gstreamer pipeline to convert the USB HDMI capture to the rtspclientsink: gst-launch-1.0 v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1,format=MJPG ! rtspclientsink location=rtsp://localhost:8554/mystream

This works great with just the test video source that the capture card creates, but as soon as I plugin an HDMI source to actually start capturing the HDMI signal, VLC ( I am using this to view the stream), completely blanks out and soon disconnects. When I look at how much network bandwidth is being used, it is around 100Mbits/sec, not the 150Mbits/sec that this card creates. I was wondering if there is something that limits the bandwidth inside of the rtsp server that can be changed or edited to make this work? Side note: I can view the full network stream perfectly fine when using tcpserversink in the gstreamer pipeline, so I know it is not a network problem between my computer and my Linux board. Any help with this would be greatly appreciated. Thank you!

**Comment by aler9** [comment]
Hello, we have to identify the place where the streams gets truncated. I have an hypothesis (the stream could get truncated if rtspclientsink sends UDP packets with a size greater than the MTU, they get truncated and don't get reassembled), but it must be verified.

try switching to TCP and see if there's a difference:
```
gst-launch-1.0 v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1,format=MJPG ! rtspclientsink location=rtsp://localhost:8554/mystream protocols=tcp
```

thanks

**Comment by aler9** [comment]
I can confirm that high bitrates have problems with UDP; please use TCP for both recording

```
gst-launch-1.0 v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1,format=MJPG ! rtspclientsink location=rtsp://localhost:8554/mystream protocols=tcp
```

and playing
```
vlc --rtsp-tcp rtsp://localhost:8554/mystream
```

and confirm that the problem disappears.

In the meanwhile i'll try to solve the problem with UDP too.

**Comment by aler9** [comment]
I did some other tests, and the problem is more complex than i thought.

I increased the the kernel read buffer, that is the buffer that keeps UDP frames that have not been read yet, this should mitigate the problem, but it is only one of a series of changes that need to be implemented and tested to increase the throughput of UDP.

At the moment, frames are read from publishers and written to readers in the same routine (thread) - this seems to saturate the read buffer, and the result is a lot of packets getting lost. A solution could be using a routine to read packets from publishers, put the packets in a queue and use another routine to write them to each publisher.

The problem is performance - doing this could undermine a series of optimizations that have been done to minimize CPU consumption, so it must be done carefully.

**Comment by zevarito** [comment]
Not sure if related but I got similar problems doing `rtspclientsink` from RTP packets on the same machine and sinking into rtsp-simple-server with UDP, Audio/Video is playable for a few seconds then UDP connection closes. I would try to give more information when back to iterate over it.

**Comment by windows10luke** [comment]
> I can confirm that high bitrates have problems with UDP; please use TCP for both recording
> 
> ```
> gst-launch-1.0 v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1,format=MJPG ! rtspclientsink location=rtsp://localhost:8554/mystream protocols=tcp
> ```
> 
> and playing
> 
> ```
> vlc --rtsp-tcp rtsp://localhost:8554/mystream
> ```
> 
> and confirm that the server works.
> 
> In the meanwhile i'll try to solve the problem with UDP too.

I can confirm that using TCP fixes the issue for me as well.

**Comment by aler9** [comment]
Now readings and writings are performed in two separate routines - this increases UDP throughput a lot, it can't reach the TCP one but at the moment i don't know what to do about it.

**Comment by Lakedaemon** [comment]
When updating the ringBuffer, are you still using a mutex/lock or are you using atomicity ? 
Is there synchronization going on ?
Are you using all cores ?

**Comment by aler9** [comment]
atomicity without mutex. All cores can't be used, there's a single reader and a single writer for each client - i took into consideration the possibility of instantiating multiple writers for each client (in this way using all cores), but the problem is that in this way packets are sent without an order, and newer could get sent before older.

**Comment by aler9** [comment]
added in v0.13.2

**Comment by Lakedaemon** [comment]
You have 1 coroutine for the producer
suspend fun produceNewFrame()

You have 1 coroutine for each reader

suspend fun pushFrameToReader() {
   while true:
        frame = produceNewFrame() // execution is suspended when the producer has no new frame 
        write frame to the reader // execution suspend if the reader is not ready to accept a new frame
 }
}

Coroutines naturally respect the sequential order of the frames, and also naturally implement backpressure 
(if the reader is not ready to accept many frames, execution is suspended, there is no buffer growing)

Also, the compiler does all the coroutine magic. Which means that 
If a core is free, it executes a starting coroutine on it (you can tune the way coroutine are dispatched on threads/thread pools).

That way, by running your coroutines on (a pool backed) threads, you automatically have parallelism while keeking the order of your frames.

Still, because your coroutine might run in threadA, then be suspended while waiting for a new frame and then continue on threadB, you have to make sure to use methods/stuff that don't get messed up by this thread jumping behavior (but there are ways) like 

for example, if you use a necessaryObject that is not thread safe, 
you have a map : thread-> necessary object 

and at a resume point of your coroutine, you do
necessaryObject = map[currentThread]
and you can use the methods of your necessary objectObject in your code
till the first suspend point (where it can jump thread)

It is wastefull to instanciate many threads/coroutines for one reader as it indeed messes the correct sequence order. The correct way is to have 1 Coroutine by reader and to make it use a core as soon as it can.

**Comment by aler9** [comment]
> That way, by running your coroutines on (a pool backed) threads, you automatically have parallelism while keeking the order of your frames.

and that's exactly what Go does, if you haven't learned it yet you should :)

> It is wastefull to instanciate many threads/coroutines for one reader as it indeed messes the correct sequence order

i've recently read a Cloudflare blog posts which describes how they increase performance by using multiple routines that read from the SAME socket in parallel, so probably it has a sense:

https://blog.cloudflare.com/how-to-receive-a-million-packets/

**Comment by Lakedaemon** [comment]
Indeed. Thanks for the enlightement. I learned something, again.

I'm a Kotlin developer.
Kotlin might become a concurent to go somewhere in the distant time (it has a native target)
Kotlin borrowed coroutine from go in it's design (very nice).
As it is possible to code in Kotlin for mobile app, the browser, native targets...I'm not sure I'll ever delve into go (especially if rtsp-simple-server 1.3.2 solves the issue I was having)

Best regards and thanks for rtsp-simple-server,
Olivier
