### ISSUE TITLE
Multiple usernames and passwords for viewing

### ISSUE THREAD

**Issue by ringtailedfox** [aler9/rtsp-simple-server#1270]
## Describe the feature

I was wondering if it's possible to allow for different username/password combinations for reading the video feed...

**Comment by aler9** [comment]
Hello, if you need a more advanced authentication mechanism you can implement an external authentication server as described in the README:

https://github.com/aler9/rtsp-simple-server#authentication

We don't plan to improve the current authentication mechanism since most users need either a basic solution or a fully-customized one.
