### ISSUE TITLE
Add a field  sessionid to externalAuthenticationURL 

### ISSUE THREAD

**Issue by huangfuhao** [aler9/rtsp-simple-server#1291]
Add a field sessionid, in order authentication server to bind user with sessionid, it will be used when authentication server disconect a session.
{
  "ip": "ip",
  "user": "user",
  "password": "password",
  "path": "path",
  "action": "read|publish"
 "sessionid ":"xxxxxxxxx"
}

**Comment by aler9** [comment]
Hello, this is actually not possible.

The external authentication server is used with all protocols, most protocols assign a unique ID to each reader (RTSP, RTMP, WebRTC) except HLS: in HLS, readers can't be uniquely identified, since it works by using a static HTTP server.

Use the API to monitor and eventually kick readers that can be uniquely identified.

**Comment by aler9** [comment]
I've added `protocol` and `id` to the payload that is sent to the external authentication URL, but again, keep in mind that the ID won't be available when protocol is HLS.

**Comment by aler9** [comment]
added in v0.21.2

**Comment by volkankoc** [comment]
I couldn't make ExternalAuthenticationURL. Is it enough to just give an auth url in the yaml file.
