### ISSUE TITLE
can it put into docker?

### ISSUE THREAD

**Issue by zhangliangbo** [aler9/rtsp-simple-server#13]
I download linux_amd64， then use Dockerfile build a image，then run it，I can normally push stream，but when I use vlc to receive stream, it always auto disconnected。But I can use windows_amd64 and powershell normally。May there will be a docker image?
![image](https://user-images.githubusercontent.com/14359338/83491441-555edb00-a4e4-11ea-9643-223582365d6a.png)

**Comment by aler9** [comment]
Hi, the Docker image is coming, but i suggest to launch your docker container with the `--network=host` command and try again.
I tried many times to use the port mapping feature of Docker, but the problem is that Docker sometimes changes the source port of UDP packets. So, you can:
* disable UDP and launch the docker container with `-p 8554:8554 -p 8000:8000/udp -p 8001:8001/udp`
* launch the docker container with `--network=host`

**Comment by aler9** [comment]
Docker images are ready and available at
https://hub.docker.com/r/aler9/rtsp-simple-server
