### ISSUE TITLE
Can't open stream via VLC: ERR: invalid control attribute

### ISSUE THREAD

**Issue by cavinsmith** [aler9/rtsp-simple-server#131]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Mac + Docker

```docker run --rm -it -e RTSP_PROTOCOLS=tcp -p 8554:8554 aler9/rtsp-simple-server```

## Question

Publishing stram wents well (from ffmpeg or from another source), but trying to open stream in VLC ends up in this:

```
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] connected
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] OPTIONS
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] ANNOUNCE
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] SETUP
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] SETUP
2020/11/23 08:27:25 [1/0/0] [client 172.17.0.1:51432] RECORD
2020/11/23 08:27:25 [1/1/0] [client 172.17.0.1:51432] is publishing to path 'a/b/c', 2 tracks with tcp
2020/11/23 08:27:47 [2/1/0] [client 172.17.0.1:51436] connected
2020/11/23 08:27:47 [2/1/0] [client 172.17.0.1:51436] SETUP
2020/11/23 08:27:47 [2/1/0] [client 172.17.0.1:51436] ERR: invalid control attribute (c)
2020/11/23 08:27:47 [1/1/0] [client 172.17.0.1:51436] disconnected
```

You can see I've published stream to "a/b/c" and when I'm trying to open it in VLC (rtsp://localhost:8554/a/b/c) - VLC fails and in server log I see the log above.

If I will publish stream without slashes, I will get a slightly different error:

```
2020/11/23 08:32:29 [2/2/0] [client 172.17.0.1:51460] is publishing to path 'abc', 2 tracks with tcp
2020/11/23 08:32:35 [3/2/0] [client 172.17.0.1:51464] connected
2020/11/23 08:32:35 [3/2/0] [client 172.17.0.1:51464] SETUP
2020/11/23 08:32:35 [3/2/0] [client 172.17.0.1:51464] ERR: unable to find control attribute (rtsp://localhost:8554/abc)
2020/11/23 08:32:35 [2/2/0] [client 172.17.0.1:51464] disconnected
```

**Comment by aler9** [comment]
Hello, please provide a network dump, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

thanks

**Comment by cavinsmith** [comment]
DUMP:

[dump.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5582092/dump.pcap.zip)

**Comment by aler9** [comment]
Hello, that's very strange, from the dump it looks like the server replies with random data to the OPTIONS and DESCRIBE requests, so VLC is forced to reinitialize the connection before every request (and of course it doesn't know anything about the published tracks and doesn't send any control attribute, and that's the error message)

request:

```
OPTIONS rtsp://localhost:8554/mystream RTSP/1.0
CSeq: 2
User-Agent: LibVLC/3.0.11.1 (LIVE555 Streaming Media v2016.11.28)
```

response:

```
0000   00 00 18 04 00 00 00 00 00 00 04 00 40 00 00 00
0010   05 00 40 00 00 00 06 00 00 20 00 fe 03 00 00 00
0020   01 00 00 04 08 00 00 00 00 00 00 3f 00 01 00 00
0030   08 06 00 00 00 00 00 00 00 00 00 00 00 00 00
```

request:

```
DESCRIBE rtsp://localhost:8554/mystream RTSP/1.0
CSeq: 3
User-Agent: LibVLC/3.0.11.1 (LIVE555 Streaming Media v2016.11.28)
Accept: application/sdp
```

response:

```
0000   00 00 18 04 00 00 00 00 00 00 04 00 40 00 00 00
0010   05 00 40 00 00 00 06 00 00 20 00 fe 03 00 00 00
0020   01 00 00 04 08 00 00 00 00 00 00 3f 00 01 00 00
0030   08 06 00 00 00 00 00 00 00 00 00 00 00 00 00
```

Can you please try the undockerized version and verify if the problem is still the same? in the meanwhile i'll find a way to test Docker + VLC + Mac OS X. thanks

**Comment by cavinsmith** [comment]
@aler9 I'm sorry I took your time! I haven't noticed that my 8554 port is already used by something (I dunno what it is yet!) and when I'm starting docker it's not showing any kind of warning concerning this port. Sorry again, my bad, now everyhting works like a charm!

**Comment by aler9** [comment]
No problem, one less mystery of the universe :)
