### ISSUE TITLE
WebRTC doesn't support H264 streams with B-frames

### ISSUE THREAD

**Issue by iesv** [aler9/rtsp-simple-server#1317]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

WebRTC doesn't support H264 streams with B-frames by using OBS steam.

## Describe how to replicate the issue

1. start the server
2. publish with  OBS
3. read with http://localhost:8889/stream

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by instinctualjealousy** [comment]
Set Max B-Frames to 0, and if using NVENC, disable Look-Ahead. It's simply not supported by WebRTC as stated.

**Comment by iesv** [comment]
Thank you!

**Comment by instinctualjealousy** [comment]
Also, if you get no audio over WebRTC, that's because it can't handle AAC. You'll need to script over opus conversion to ffmpeg and remux the stream. You can probably do this with runOnReady in rtsp-simple-server but I haven't got it to work for me yet. Probably misunderstanding it, myself. Anyway, you're welcome!

**Comment by t3therdev** [comment]
I was able to get it working with this in runonready:

`runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH  -vcodec copy -c:a libopus  -f rtsp rtsp://localhost:$RTSP_PORT/compressed`

**Comment by aler9** [comment]
Hello all,
I was never able to make a video with B-frames work with WebRTC, so i'm assuming that it is not supported at all, but i may be wrong, and if someone finds a technique or a software that supports it i'm ready to upgrade the server.

Anyway, videos with B-frames work correctly with Low-Latency HLS, therefore you can achieve a latency lower than 1s by using a different protocol.

**Comment by saket424** [comment]
> Set Max B-Frames to 0, and if using NVENC, disable Look-Ahead. It's simply not supported by WebRTC as stated.

Is there an explicit setting in OBS for these two? Can you send me a screenshot as it was not obvious to me where this needs to be set

**Comment by saket424** [comment]
Also, another pion-based project called broadcast-box is able to handle/decode obs whip input just fine and has a whep player. How are they handling the B-Frames?

https://github.com/Glimesh/broadcast-box
https://github.com/obsproject/obs-studio/commit/851a8c216e14617fb523951839f3bdb240e85141

**Comment by aler9** [comment]
@saket424 you're referring to the latest OBS code that allows to publish with WebRTC, while this issue is related to publishing with RTMP. In OBS, when WebRTC is used in place of RTMP, B-Frames are automatically disabled, take a look at this line:

https://github.com/obsproject/obs-studio/blob/851a8c216e14617fb523951839f3bdb240e85141/plugins/obs-webrtc/whip-service.cpp#L34

Therefore broadcast-box doesn't handle B-frames at all.

**Comment by pedrohba1** [comment]
I just wanted to add that if you are using local development and just want to remove B-frames from a video, you can do:

```
ffmpeg -i sp1.mp4 -c:v libx264 -bf 0  sp1_no_bf.mp4
```
