### ISSUE TITLE
Act as a RTMP server and support RTMP clients

### ISSUE THREAD

**Issue by io7m** [aler9/rtsp-simple-server#132]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

## Question

Hello! I'm currently using `rtsp-simple-server` to both publish and serve RTSP streams, for which it seems to work extremely well. However, I have a couple of clients that are only capable of publishing RTMP, and those currently have to go through the rather unmaintained `nginx` `rtmp` module. I'd like to retire the `nginx` server and only use `rtsp-simple-server`, but that would mean shutting out those clients that can't publish RTSP yet. Is there a way to have `rtsp-simple-server` accept an `rtmp` publication? I'm not seeing it in the documentation, which makes me think it isn't supported.

**Comment by aler9** [comment]
hello,

> Is there a way to have rtsp-simple-server accept an rtmp publication? I'm not seeing it in the documentation, which makes me think it isn't supported

at the moment the server doesn't have this feature - i have to use nginx-rtmp too to support incoming RTMP clients, and i have to support them since most web video platforms force us to use RTMP - streams are the bridged to rtsp-simple-server with the `source: rtmp://` feature.

Adding a RTMP server is a feature that can be implemented since there's a [well written library](https://github.com/notedit/rtmp) that allows to build RTMP server, but i'd like to avoid it, since this project would become more a media server than a RTSP server.

Anyway, if more people requests it, maybe it can be added in the future as an optional feature (with a parameter like `rtmpServerEnabled` or similar).

**Comment by Lakedaemon** [comment]
I will need that also : 
the ipcam I use are behind a 4G router with a not routable (private) ip adress (all cheap 4G settings are like this in France).
So, the ipcam cannot be accessed from the internet but they can push rmtp stream to the internet

**Comment by io7m** [comment]
> Adding a RTMP server is a feature that can be implemented since there's a well written library that allows to build RTMP server, but i'd like to avoid it, since this project would become more a media server than a RTSP server.

Understood!

I think this is a problem that'll eventually solve itself. Right now the situation in the ecosystem in general seems to be:

|Protocol|Client support|Server support|
|-----------|--------------------|--------------------|
|rtsp|Moderate|Good|
|rtmp|Good|Poor|
|srt|Moderate|Poor|

It's tiresome to have to lug this nginx module around just because some clients are afraid of UDP. :laughing:

**Comment by aler9** [comment]
The server now has a RTMP listener to receive legacy RTMP streams; this feature is available in main and will be added to the next release 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by io7m** [comment]
Very nice! Thanks! :tada:

**Comment by aler9** [comment]
added in v0.14.0

**Comment by t3therdev** [comment]
Awesome!
