### ISSUE TITLE
Save HLS fragments and playlist in file system (HDD/SSD) for less RAM footprint

### ISSUE THREAD

**Issue by AlienJust** [aler9/rtsp-simple-server#1322]
## Describe the feature

Is it possible to store video fragments on file system?
I have about 20 cameras and want to have access to their videos last 48h. IMO it is too many fragments to keep them RAM but would be easy with 1TB SSD :-)

**Comment by symonenkob** [comment]
+1 Would be a great feature if implemented out of the box for llhls and hls!


It is possible, however, to achieve the following behavior by using **ffmpeg** and **runOnReady** but the segments will be generated with some delay. It did not work for us because we had to synchronize livestream and the recorded video afterwards (users may trigger some events on a live video and we must reproduce them on a recorded video). I was seeing a fragments saving delay ~2.5 sec from the live stream and use of EXT-X-PROGRAM-DATE-TIME did not help because ffmpeg overrides the original time with a system time at the moment of segment generation.
The command looks like this and I am sure it can be improved a bit.
`runOnReady: ffmpeg -y -i https://localhost:8888/videostream/stream.m3u8 -c copy -f hls -live_start_index 0 -hls_list_size 0 -hls_flags +program_date_time+independent_segments  -strftime 1 -hls_segment_filename 'stream_%Y%m%dT%H%M%S%z.ts' stream.m3u8`

**Comment by aler9** [comment]
This is being implemented in https://github.com/bluenviron/gohlslib/pull/2

**Comment by aler9** [comment]
implemented here: #1567

**Comment by aler9** [comment]
added in v0.22.0

**Comment by marcosalberto** [comment]
Hi @aler9,

Does this feature allow using multiple mediamtx replicas in a load balancer to distribute resource usage?

Thanks for this great project.

**Comment by aler9** [comment]
@marcosalberto if you want to distribute the load, use a set of HTTP caching proxies (like Squid) in front of MediaMTX. The content of a folder nowadays is not enough to produce a modern HLS stream, since it doesn't allow to provide blocking request (i.e. the ability of freezing a user request until a certain playlist or segment is available) and low-latency parts (which are not saved to disk).

This feature is intended for offloading segments from RAM, since segments occupy a significant fraction of the RAM.

**Comment by marcosalberto** [comment]
@aler9 thank you, we will check about Ingress Session Affinity to accomplish that on Kubernetes enviroment.
