### ISSUE TITLE
WebRTC: Using SetEphemeralUDPPortRange for UDP port range

### ISSUE THREAD

**Issue by JeDiE99** [aler9/rtsp-simple-server#1324]
Not all UDP ports can be used for webrtc on server
example: https://github.com/deepch/RTSPtoWeb/pull/128/files

**Comment by aler9** [comment]
Hello, the parameters `webrtcICEHostNAT1To1IPs`, `webrtcICEUDPMuxAddress` and `webrtcICETCPPMuxAddress` have been added to the server and allow to use a fixed UDP or TCP port in order to accept ICE connections. Instructions are in the README:

https://github.com/aler9/rtsp-simple-server#usage-inside-a-container-or-behind-a-nat
