### ISSUE TITLE
Grey Frame when reading stream

### ISSUE THREAD

**Issue by lkinfotechai** [aler9/rtsp-simple-server#1328]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
when i receive stream from rtsp-simple-server
server works well and make connection with client as well ( client i am using vlc/ffmpeg)

but during stream play i am getting grey frame on most of the stream. at that time i see the logs came like 2 RTP Packet Lost, 4 RTP packet lost like that.
this case is mostly came when i am using UDP protocol in rtsp stream

## Describe how to replicate the issue

1. start the server
2. publish with RTSP
3. read with vlc/ffmpeg client

## Did you attach the server logs?

no

the main point in logs are
2 RTP Packet Lost
4 RTP Packet Lost
10 RTP Packt lost

## Did you attach a network dump?

no

**Comment by mohseni-fatemeh** [comment]
hello 
this is also my problem .
os : jetson-desktop 4.9.299-tegra

**Comment by aler9** [comment]
Hello, the log says it all:

```
2 RTP Packet Lost
4 RTP Packet Lost
10 RTP Packt lost
```

Packets are lost during transfer from server to VLC. Make sure that your network infrastructure is capable of handling the video you want to stream, otherwise decrease the video bitrate or use one of the techniques described in the [README](https://github.com/aler9/rtsp-simple-server#corrupted-frames) in order to mitigate the issue.
