### ISSUE TITLE
trouble with yaml

### ISSUE THREAD

**Issue by Lakedaemon** [aler9/rtsp-simple-server#133]
## Which version are you using?

v0.12.1

## Which operating system are you using?

 Linux

## Question

I have problems configuring rtsp-simple-server as a proxy for an ethernet cam with rtsp capabilities

I have linked through ddns "SomeSite" to the dynamic ip of my router.
On this router, I do port forwarding 8554 to the 554 port of my ip cam with rtsp

I can acess the video stream through vlc, with 
rtsp:// 192.168.1.168:554/ipc
rtsp://SomeSite:8554/ipc

yet, when I do 
paths:
  proxied:
     source: rtsp://SomeSite:8554/ipc
     sourceOnDemand: yes

it fails miserably when I try to access the video stream in the vps with the stream sever through

rtsp://MyVps:8554/proxied

I get those errors : 
rtsp source ERR: server ports not provided

I also tried

paths:
  proxied:
     source: rtsp://user:pass@SomeSite:8554/ipc
     sourceOnDemand: yes

And I get the same error

Can you please give me some pointers ?

**Comment by Lakedaemon** [comment]
I have tested some more
when I open rtsp://someSite:8554/somePath/trackID=0 in vlc,
the stream server complains that the controlpath  trackid=0 is invalid (it is not prefixed by trackID because there are no caps)

Also, I don't know what trackID is (I have an ipcam with a main and a secondary stream, maybee this is it ?)

**Comment by aler9** [comment]
Hello, in my opinion you can fix this problem immediately by using the `sourceProtocol: tcp` parameter:

```yml
paths:
  proxied:
    source: rtsp://user:pass@SomeSite:8554/ipc
    sourceOnDemand: yes
    sourceProtocol: tcp
```

Regarding the case in which sourceProtocol is udp (the default value), it's a communication bug between the server and the camera, please to the following:

The most helpful content you can provide to fix a communication issue between rtsp-simple-server and an external hardware or software, is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by Lakedaemon** [comment]
I'll try both things. Thanks for the help

**Comment by Lakedaemon** [comment]
in vlc, if I open with rtsp://site:8554/proxied   it complains that there is no control attribute
if I open with rtsp://site:8554/proxied?/trackID=0  it complains that the control attribute is invalid

Maybe it fails before it uses the source configuration

I was using 
protocols: [tcp]

so udp is not an issue, probably (I'm a beginer in tcp.udp/network thingies so...I might be wrong)

what is a control attribute ?

I'll try with wireshark next, I remember using that in the past like 10+ years ago

**Comment by aler9** [comment]
let's try to find where the bug is, ok?

From what i understood, this is your setup:

```
camera --> router -> dns (dyndns or similar) -> rtsp-simple-server -> vlc
```

can you post the log of `rtsp-simple-server`, so we can understand if the stream arrives or not?
If the log contains something like
```
rtsp source is ready
```

it means that the stream arrives to the server - afterwards, you can test VLC (do not add trackID=0 to the path, it's useless).

**Comment by Lakedaemon** [comment]
Indeed, I have
1) camera -> local routeur (behind a dynamic ip)

2) vps with rtsp-simple-server (acting like a rtsp proxy)

3) I open on my local comp connected to the local routeur in vlc with rtsp://vps:8554/proxied

when doing rtsp://vps:8554/proxied

I get (in standard out, 83.154.205.190 is my dynamic ip today)

020/11/25 23:03:13 [0/0/0] rtsp-simple-server v0.12.1
2020/11/25 23:03:13 [0/0/0] [TCP server] opened on :8554
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] connected
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] OPTIONS
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] DESCRIBE
2020/11/25 23:03:28 [1/0/0] [path proxied] rtsp source started
2020/11/25 23:03:28 [1/0/0] [path proxied] connecting to rtsp source
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] connected
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] SETUP
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] ERR: unable to find control attribute (rtsp://vps:8554/proxied)
2020/11/25 23:03:33 [1/0/0] [client 83.154.205.190:33522] disconnected
2020/11/25 23:03:38 [1/0/0] [path proxied] rtsp source ERR: dial tcp 83.154.205.190:554: i/o timeout
2020/11/25 23:03:38 [1/0/0] [client 83.154.205.190:33520] ERR: publisher of path 'proxied' has timed out
2020/11/25 23:03:38 [0/0/0] [client 83.154.205.190:33520] disconnected
2020/11/25 23:03:43 [0/0/0] [path proxied] connecting to rtsp source
2020/11/25 23:03:48 [0/0/0] [path proxied] rtsp source stopped

**Comment by aler9** [comment]
```
2020/11/25 23:03:28 [1/0/0] [path proxied] rtsp source started
2020/11/25 23:03:28 [1/0/0] [path proxied] connecting to rtsp source
2020/11/25 23:03:38 [1/0/0] [path proxied] rtsp source ERR: dial tcp 83.154.205.190:554: i/o timeout
```
this means that the server is unable to contact your camera - check routers / nat / firewalls in between.

```
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] connected
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] OPTIONS
2020/11/25 23:03:28 [1/0/0] [client 83.154.205.190:33520] DESCRIBE
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] connected
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] SETUP
2020/11/25 23:03:33 [2/0/0] [client 83.154.205.190:33522] ERR: unable to find control attribute (rtsp://vps:8554/proxied)
2020/11/25 23:03:33 [1/0/0] [client 83.154.205.190:33522] disconnected
```
This is VLC, that connects to the server, and waits for the stream without receiving any answer (since the server is unable to contact the camera). When VLC doesn't receive any answer, after a timeout it supposes that server has an old RTSP implementation, and tries to communicate with it by stripping important parts of the protocol (like the control attribute).

Therefore: these issues should be both solved when i'll be able to contact your camera from the server.

**Comment by aler9** [comment]
PS: try removing the `sourceOnDemand: yes` parameter, so the server connects to the camera before VLC connects to the server - maybe it helps.

**Comment by Lakedaemon** [comment]
I see. This helps a lot.
I'll look also in the port forwarding things of my router.

Best regards and have a good night. and many many thanks for the enlightement.

**Comment by Lakedaemon** [comment]
Oh. With your kick ass explanations, It juste took me like 2 minutes to get the rstp proxy up and running.
Awesome (I love you).
My students are going to really like your software (and maybe a whole bunch of french teachers too ^^)

**Comment by austineDboss** [comment]
> Oh. With your kick ass explanations, It juste took me like 2 minutes to get the rstp proxy up and running.
> Awesome (I love you).
> My students are going to really like your software (and maybe a whole bunch of french teachers too ^^)

How did you resolve this issue if I may ask? Thanks !
