### ISSUE TITLE
Support for Opus through HLS 

### ISSUE THREAD

**Issue by owlnull** [aler9/rtsp-simple-server#1338]
## Describe the feature

HI! It would be nice to add support for Opus codec through HLS

**Comment by aler9** [comment]
Hello, thanks this feature request, i didn't knew that HLS could play Opus, but it turned out that recent versions of hls.js, Firefox and Chrome allow to read Opus tracks inside MP4 segments.

Reading Opus tracks with HLS is now fully supported.

The implementation is based on this [specification](https://opus-codec.org/docs/opus_in_isobmff.html).

**Comment by aler9** [comment]
This is now supported since v0.21.1
