### ISSUE TITLE
RTSP Streaming from ffmpeg with audio codec of pcm_16le returns error

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#1350]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [x] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Pushing rtsp from a usb camera and alsa audio source with acode set to pcm_s16le gives, error but pcm_s16be works and causes high cpu.

## Describe how to replicate the issue

1. start the server

2. publish with with ffmpeg usb camera and alsa audio:
ffmpeg -f alsa -i plughw:0,0 -acodec pcm_s16le -channels 1 -ar 8000 -b:a 96k -f rtsp -rtsp_transport tcp rtsp://localhost:8554/
cam

3. error occurs:
2022/12/29 21:57:10 INF [RTSP] [session 318644919] created by [::1]:34428
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request
Error initializing output stream 0:0 --

Using pcm_s16be does work, but seems to cause encoding to increase in cpu to the point where its unusable:

ffmpeg -f alsa -i plughw:0,0 -acodec pcm_s16be -channels 1 -ar 8000 -b:a 96k -f rtsp -rtsp_transport tcp rtsp://localhost:8554/
cam

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by chip131001** [comment]
I have a similar scenario. I have an IP camera and a Raspberry with a microphone and speakers.
I use the following command to stream.

`ffmpeg
        -f alsa -ac 1 -i default
        -i rtsp://192.168.178.183:8554/eingang
        -preset ultrafast -tune zerolatency
        -c:v copy
        -c:a libfdk_aac -ac 2 -ab 32k -ar 44100
        -f rtsp rtsp://localhost:8554/mic?pkt_size=1316`

I would like to implement a door intercom with it.
But I get a lot of warnings.
Is there a better way to implement this?

<img width="1503" alt="Bildschirm­foto 2023-01-04 um 19 31 10" src="https://user-images.githubusercontent.com/38818613/210625504-39ba521b-e2a0-49c1-86bf-7b12938b91d3.png">

**Comment by aler9** [comment]
Hello @t3therdev,
Currently there isn't a defined RTP standard that explains how to send little endian LPCM with RTP/RTSP.

FFmpeg doesn't have little endian LPCM in the list of codecs that can be used in order to generate a SDP (needed in order to publish tracks in RTSP):
https://github.com/FFmpeg/FFmpeg/blob/4a054c3e97b4f30fe517114e381f9a2ee5a92f7c/libavformat/sdp.c#L512

and therefore it generates an invalid SDP without the track details:

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.76.100
m=audio 0 RTP/AVP 96
b=AS:128
a=control:streamid=0
```

At the same time, FFmpeg still sends out the track's content:
https://github.com/FFmpeg/FFmpeg/blob/efbe84eb1b74a80cd12174feaaa37da2e8fb1e66/libavformat/rtpenc.c#L548

But no one knows that the stream is using little endian LPCM (because FFmpeg didn't announced it) and consequently no one knows how to parse it.
