### ISSUE TITLE
API request for webrtc offer

### ISSUE THREAD

**Issue by JeDiE99** [aler9/rtsp-simple-server#1376]
## Describe the feature
Add API request thats send local SDP offer (from browser) to rtsp-simple-server and return remote SDP offer (for browser).
It be useful to get webrtc stream without internal html ([main/internal/core/webrtc_index.html](https://github.com/aler9/rtsp-simple-server/blob/main/internal/core/webrtc_index.html)) and use https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription in custom javascript code directly with full control/flexability.
Or it will be userful for other webrtc destination (not browser)

**Comment by aler9** [comment]
Hello, there's already a way to send local SDP offer from the browser to the server, and consists in using WebSocket like in the sample file you linked. I know it's currently undocumented, but it will be.

Nowadays sending the initial SDP offer to the counterpart is not enough in order to establish a connection between two WebRTC peers, since browsers generate candidates asynchronously, after the local SDP offer has been sent to the server. These candidates must be sent to the server too, and using WebSocket is the most efficient way to do so.

Furthermore, the current WebRTC implementation is not good at detecting whether the connection is still active or not (i don't know yet if it's a browser issue or a server issue), therefore the WebSocket connection is kept alive and monitored in order to detect disconnections. If it dies, the WebRTC connection is restarted. If wouldn't be possible if we use only an HTTP API.

**Comment by JeDiE99** [comment]
Thank for response!

**Comment by JeDiE99** [comment]
Thank for response!
