### ISSUE TITLE
Support reading h265 with Webrtc

### ISSUE THREAD

**Issue by pikachu937** [aler9/rtsp-simple-server#1448]
## Describe the feature
Todo:
- [ ] add support for h265 into webrtc_conn
- [ ] or realtime transcode from h265 to h264 for playng video over webrtc

You answer in issue [1438](https://github.com/aler9/rtsp-simple-server/issues/1438), but i can't understand why? in logs of server i have:
> closed (the stream doesn't contain any supported codec (which are currently VP9, VP8, H264, Opus, G722, G711))

I tested safari, chrome, firefox on my mac and doesn't work webrtc h265.
many cameras broadcast only in h265 (all my cameras broadcast only in h265), I can only watch them via rtsp, this is not very convenient and webrtc can come to the rescue.
many cameras broadcast only in h265 (all my cameras broadcast only in h265), I can only watch them via rtsp, this is not very convenient and webrtc can come to the rescue.
in addition, the output you describe is not acceptable, because it creates a large load on the CPU, especially if there are 500 streams on the server, and also increases the already large delay and the video is essentially not real-time

**Comment by aler9** [comment]
I repeat: it's not a server limitation, it's a browser limitation. All browsers except Safari don't support H265 through WebRTC. I can't do anything about it.

The server is not able to stream H265 through WebRTC and there's no need to develop the feature for the reason explained above.

**Comment by pikachu937** [comment]
As I wrote above, this does not work in safari either.  I'm developing my smartphone app for ios and android, how can I use rtsp-simple-server to display video via webrtc?  Or maybe you can do real-time transcoding?

**Comment by aler9** [comment]
For the third time: H265 inside WebRTC is currently supported by Safari only, therefore server support inside rtsp-simple-server has not been developed because there are currently not enough reasons to do it.

You can transcode from H265 to H264 at any moment by using FFmpeg, as described in the README:

https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression

**Comment by mateothegreat** [comment]
The problem **is** that you're combining two _separate_ problems.

Problem #1: Not fully understanding the _actual_ problem: You're sourcing at H.265 but you need to broadcast at H.264 -- two separate things.

Problem #2: You're trying to shove H.265 straight away down to the browser and are expecting it to "work" because we're using WebRTC (the all-being illusive answer to all streaming questions 🔨 ).

As @aler9 indicated, he is correct here.

You have three options:
1. Inject a transcode in your pipeline to make the in become the out you need.
2. Don't put all your eggs in one basket with WeRTC (it solve __one__ problem) by breaking out streams based on requirements (i.e.: H.264? Go to town over WebRTC. H.265? Use an HLS approach with small segments).
3. Add in the missing parts around https://github.com/bluenviron/mediamtx/blob/main/internal/core/rtmp_source.go#L127 to kick off the process 🤌 and submit a pr.

I've had to overcome this very issue, several times and at scle. It's not pretty but given the needs of the many over the few this will be the status quo for a while unless you submit that PR @pikachu937 ;)

**Comment by aler9** [comment]
Streaming H265 with WebRTC is now supported with #4003
