### ISSUE TITLE
v0.13 PAUSE issue

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#157]
## Which version are you using?

v0.13.0

## Which operating system are you using?

OS

- [ X] Linux

Architecture

- [ X] amd64

Description

v.0.13 seems to have changed/broken how the PAUSE request is handled for me. Previously in v0.12.2 when the client is subscribing to a UDP source and issues a PAUSE request, the following action of PLAY/UNPAUSE would resume the feed with the latest data available, ie/ no caching, buffering.

In version 0.13 this doe not seem to be the case. 

Replicate issue with v0.12.2 and v0.13. 

1. start the server
2. publish with ffmpeg -re -stream_loop -1 -i testfile.mp3 -vn -c:a libopus -ab 64k -f rtsp rtsp://127.0.0.1:554/test 
3. read with 2 instances of ffplay rtsp://127.0.0.1:554/test
4. Issue PAUSE request on ffplay_1
5. Resume play on ffplay_1
6. Ffplay_1 should be in sync with ffplay_2

**Comment by aler9** [comment]
i was waiting for some important issues, there are too many changes in the software architecture between this version and the previous one :)
The issue seems to happen only with UDP streams, try this nightly release
[rtsp-simple-server_v0.13.0-3-gb3e9249_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5705602/rtsp-simple-server_v0.13.0-3-gb3e9249_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.13.0-3-gb3e9249_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5705603/rtsp-simple-server_v0.13.0-3-gb3e9249_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5705604/rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5705606/rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5705607/rtsp-simple-server_v0.13.0-3-gb3e9249_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.0-3-gb3e9249_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5705608/rtsp-simple-server_v0.13.0-3-gb3e9249_windows_amd64.zip)

**Comment by bbnp91** [comment]
Great thanks,
Yes, the problem is resolved in the nightly release you provided :)

**Comment by aler9** [comment]
added to v0.13.1
