### ISSUE TITLE
Support for ROS video streams as an input

### ISSUE THREAD

**Issue by Chambana** [aler9/rtsp-simple-server#1591]
## Describe the feature

ROS (Robot Operating System) is a messaging passing framework used in many/most robots.  Video streams are handled natively in ROS1 by passing a stream of messages of [this type](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/Image.html).  It would be great if RTSP-simple-server could ingest ROS video streams just like other inputs that work with RTSP-simple-server.  

The flow might resemble something like this:
- the rtsp-simple-server config file sets the ROS_MASTER_URI to the ROS master's IP:port
- the rtsp-simple-server config file sets the specific ROS topic to subscribe to (e.g. "/some_image_topic")
- the rtsp-simple-server uses the above config file params and spins up a simple python or C++ ROS subscriber.  It then "just" relays the ROS video stream's image frames into the RTSP server pipeline

P.S. Would be great if this supported ROS2 as well, which eliminates the need for the ROS_MASTER_URI step above.

**Comment by aler9** [comment]
Hello, this would be an amazing feature since i'm also the author of a popular [ROS porting for Go](https://github.com/bluenviron/goroslib), there are however major issues:

* spinning up subscribers in Python or C++ is not portable nor compatible with all the OS that the server supports, therefore there would be compatibility issues. The only way to implement the ROS part in a portable way is by using a Golang library like goroslib
* goroslib doesn't support yet ROS2, implementation is currently too challenging since it involves writing a DDS implementation in Go and there's not enough interest from any stakeholder (public / companies / organizations) into sponsoring the development. Interest in video streaming is 20x higher.

Therefore, this feature request will probably remain blocked until the ROS2 - goroslib integration is developed, but again,  it's totally blocked:
https://github.com/bluenviron/goroslib/issues/36

**Comment by Chambana** [comment]
Bummer, but thanks for the well informed response!
In the meantime, if you have any suggestions for a turnkey solution to achieve the same results (some transcoding solution to ingest ROS and output something RTSP-simple-server can read), I'd be all ears.  
Happy to close this feature request if you'd like.
