### ISSUE TITLE
Feature Request: Create a docker image and upload to Docker Hub

### ISSUE THREAD

**Issue by givo** [aler9/rtsp-simple-server#16]
Hi,

This is a really good project and I think a lot of us would love to use it using docker.
Can you please create a docker image and upload it to docker hub?

Thank you!

**Comment by flaksirus** [comment]
I don't know why but I've tried this and some other rtsp servers with docker containers and none of them worked really... My host system is Windows so I tried WSL2 docker and docker on ubuntu server and none of them worked well (they do connect but stream fails before first frame seen). The same time all of them hosted without docker works just fine (even on WSL).
Am I the only one who got this kind of problem?

**Comment by aler9** [comment]
Hello, hosting a RTSP server inside a Docker container is problematic since Docker can, in certain situations, change the source port of UDP packets, making RTSP-via-UDP unreliable, since UDP packets are identified and routed by a RTSP server by looking at their source IP and port.

There are two ways to solve the problem:
* create the container with the --network=host flag
* expose the TCP port (-p 8554), and disable the UDP protocol (in rtsp-simple-server, this is done with the --protocols=tcp flag)

Anyway, a docker image for rtsp-simple-server is on its way.

**Comment by aler9** [comment]
Docker images are ready and available at
https://hub.docker.com/r/aler9/rtsp-simple-server
