### ISSUE TITLE
on demand command does not stop as expected?

### ISSUE THREAD

**Issue by dlueth** [aler9/rtsp-simple-server#185]
## Which version are you using?

v0.13.2

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [x] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

It seems as if on demand commands will not be stopped as expected. I do start ffmpeg and pipe its output into gstreamer (which than provides the rtsp-stream) for testing as an onDemand path. The server starts the command just fine but when the client disconnects (and CLI output says `on demand command stopped`) both ffmpeg and gstreamer processes are still running and will only get terminated when rtsp-simple-server is stopped.

## Describe how to replicate the issue

1. configure a path with `runOnDemand`
2. start the server
3. start a client requesting the path
4. stop the client
5. wait for the server to ouput `on demand command stopped`
6. check if command was really stopped

**Comment by dlueth** [comment]
@aler9 Reported this being on v0.13.2 and just double-checked it on master: still present.

My Go knowledge is not good enough to debug this myself, sadly enough. already tried...

Or I am probably wrong:
My assumption was that `runOnDemand` command gets started when the first client connects and it gets stopped 10s after the last remaining client disconnects if there is no new connection within timeout.

**Comment by mdabbs** [comment]
I hate to resurrect a closed issue, but I'm having trouble with this exact issue. I have a runOnDemand that executes a bash script. The script launches a capture program that writes to stdout and that is piped into ffmpeg which pushes the stream to the server. I see in the rtsp-simple-server log a message that says runOnDemand command stopped, but none of the bash script, capture program, or ffmpeg are actually stopped.  Do I need to do something different because 3 things are actually running?  And as maybe a feature request, could there instead be a runOnClosed where I could then just run a script that would know how to tear everything down? Thanks.
