### ISSUE TITLE
Need for maxLogSize: *[B|K|M|G] and logOverwrite: [true|false] options

### ISSUE THREAD

**Issue by brandousov** [aler9/rtsp-simple-server#252]
## Which version are you using?

v0.15.2

## Enhancement request

Hi! Thanks for `sourceProtocol: automatic`! We have another problem with log size - some VLC and other clients (and our development/testing teams builds too) are configured for auto-reconnect if fails and this is good, but our logs for the last week grows up to150 GB each... this happens with daily logrotate enabled.

So add please i f possible 2 new directives:  
```
maxLogSize: 777M
logOverwrite: true
```

- if max logSize is set and overwrite true - replace older recors with new, if overwrite is false - stop logging with console warning.

**Comment by aler9** [comment]
Hello, this is a feature that is being requested a lot, the problem is that i don't want to implement a feature that is normally handled externally by logrotate or systemd or even logstash.
If you need all that log, in my opinion you should setup one of
* logstash
* fluentd
* kafka
to handle it, and at the same time truncate the log file every hour.
