### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by x-jokay** [aler9/rtsp-simple-server#32]
What about doing a release for more than one fix, feature or even commit? :roll_eyes:

What is the purpose / intention of having 3 or more releases on one day? :wink:

**Comment by aler9** [comment]
Hello, there are multiple reasons:
* in bigger projects there's a group of people that test the software before the release, while here we're still a small group of people, so real testing can be done only after a release is published, otherwise bugs cannot be found
* i use continuous deploy in production and always need the latest version of the code
* last week a certain number of new features were added (configuration file, scripts, new libraries for SDP, RTCP and RTSP)

Nonetheless my aim is to stop adding new features and provide a very basic, finished tool. This project will never become a media server, that would require years to complete, with issues being created every year, this will remain a very basic RTSP server and hopefully be completed soon. Releases will be much more infrequent from now on.
