### ISSUE TITLE
VLC  - ERR: path must end with a slash

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#352]
## Which version are you using?

v0.15.4

## Which operating system are you using?

OS

- [ ] Linux
- [X] Windows
- [ ] macOS

## Describe the issue

Setup a simple brand new installation of 15.4. Change all paths to ch500. Set source as an rtsps stream such as rtsps://ipaddress/ch500
path will be non rtsps (source is rtsps)

Connect with VLC:
ERR: path must end with a slash

Connect with ffplay, works fine. along with other clients.

**Comment by aler9** [comment]
Hello, to check this i need the server logs up to the point that VLC tries to read the stream.

**Comment by Enverex** [comment]
Seeing the same thing. If you put in the URL as is, you get...

`ERR: path must end with a slash (mypath)`

So you add a slash, but then you get...

`ERR: invalid path name: can't end with a slash (mypath/)`

Getting mixed messages here.

**Comment by aler9** [comment]
No one provided logs to analyze the issue, but anyway this is probably what is happening:

1. the server tries to establish a connection to the source (the camera), but it can't since the camera can't be reached
2. a client (VLC?) tries to connect to the server, but the server hasn't established a connection to the source yet, and it rejects the client; VLC tries a fallback, unsupported protocol and this generates the error path must end with a slash (test)

Make sure that the server can reach the camera and wait for the log message

```
[rtsp source] ready
```

Regarding the error, a little improvement could be writing it in another way, such as

```
ERR: client is using an unsupported version of RTSP that doesn't use Content-Base
```

**Comment by tprins228** [comment]
What logs do you need and how do I pull them?  I'm having the same issue running the docker image on a raspberry pi and trying to access via vlc on Windows.

**Comment by tprins228** [comment]
What logs do you need and how do I pull them?  I'm having the same " ERR: path must end with a slash" while running the docker image on a raspberry pi and attempting to access via VLC on a Windows machine.

**Comment by aler9** [comment]
Just provide the server logs, that can be saved to a file by adding `logDestinations: [stdout, file]` to the configuration.

**Comment by tprins228** [comment]
attached are logs and config file (in text format)
[rtsp-simple-server.txt](https://github.com/aler9/rtsp-simple-server/files/6609697/rtsp-simple-server.txt)
[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/6609685/rtsp-simple-server.log)
