### ISSUE TITLE
onDemand RTSP: First consumer works, second gets no image

### ISSUE THREAD

**Issue by eLvErDe** [aler9/rtsp-simple-server#353]
## Which version are you using?

v0.15.4

## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Sometimes, we are not exactly sure when it happens, when multiple consumer are connected to the same stream, only first one get images, second one gets nothing but no error either.

## Describe how to replicate the issue

We've have been able to replicate the issue with one camera by connecting it to Janus WebRTC server as first consumer, then attempt to read the stream using VLC => no image.

Sadly it's probably going to be hard to replicate but I'll email you a wireshark dump from the machine running RTSP server filtered with camera source IP and VLC non-working client IP.

## Did you attach a network dump?

Check your mailbox.

Thanks in advance,

Best regards, Adam.

**Comment by eLvErDe** [comment]
Ok more information, there's definitely a bug.
Turns out after a big of shell magic against the log files, most of the error we had were related to streams having two tracks.
I just fixed a bunch on sony and axis devices that had audio enabled to disable it and we have no more issues with them.

**Comment by t3therdev** [comment]
Yes we are seeing a similar issue with dual track streams.

**Comment by aler9** [comment]
Hello, in my opinion this was caused by a race condition that occurred during the computation of RTP-Info; please try this nightly release and confirm that the issue has been solved.
[rtsp-simple-server_v0.15.4-6-g8b3cd43_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6329189/rtsp-simple-server_v0.15.4-6-g8b3cd43_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6329190/rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_amd64.tar.gz)
[rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6329191/rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm6.tar.gz)
[rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6329192/rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm7.tar.gz)
[rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6329194/rtsp-simple-server_v0.15.4-6-g8b3cd43_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.15.4-6-g8b3cd43_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/6329195/rtsp-simple-server_v0.15.4-6-g8b3cd43_windows_amd64.zip)

**Comment by aler9** [comment]
Turned out that there was a much more serious issue: the video track was receiving audio, while the audio track was receiving video. This happened because of this conversion from a map to an array:

https://github.com/aler9/gortsplib/blob/805d578b6c63bce5f23a91e52c097d98a4a93e11/clientconn.go#L256

Since maps are unordered, during the iteration, track 1 (audio) could appear before track 0 (video), resulting in the inversion.

sort() was added to solve the issue:

https://github.com/aler9/gortsplib/blob/805d578b6c63bce5f23a91e52c097d98a4a93e11/clientconn.go#L260

Added in v0.15.5

**Comment by eLvErDe** [comment]
Seems all our remaining problems are gone with latest release.

Thanks a lot!
