### ISSUE TITLE
Glitch video when loading stream the first time or when second client connects to an RTSP Stream

### ISSUE THREAD

**Issue by cothingsusr** [aler9/rtsp-simple-server#371]
## Which version are you using?

v0.15.5

## Which operating system are you using?
- [ ] Linux
- [x] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Using ffmpeg to push RAW video stream (as publisher), when a client connects, most of the time the first 4/5 seconds the video is displayed in Glitch mode.
Same behavior when a second client connects to an existing stream, the second client gets the first 4/5 seconds in Glitch mode

## Describe how to replicate the issue

1. start the server
2. publish raw video with ffmpeg (input raw) -c:v libx264 -preset ultrafast  -f rtsp rtsp://localhost:8554/ 

3. Open the rtsp using vlc

![err2](https://user-images.githubusercontent.com/16971218/116822552-5fb3aa00-ab77-11eb-8056-2ef7a407ae8a.PNG)

![img_error](https://user-images.githubusercontent.com/16971218/116822569-71954d00-ab77-11eb-91ac-3bbf41309470.PNG)

**Comment by aler9** [comment]
Hello, this is an issue that is typical of H264/H265 streams - the server doesn't apply any codec-specific filtering, therefore if we have a stream like this

```
P P P I P P P I
```

Where P is a predicted frame and I is an Intra-coded frame, the server sends it as it is, and the player is unable to decode the first 3 frames since they depends on a previous I-frame that wasn't sent.

A solution could be adding an algorithm in the server that drops any P or B frame until an initial I-frame is sent, but the problem of this solution is that it depends on the interval of the I-frames, and if this interval is too big, the client goes in timeout mode (especially VLC, that drops the connection if it doesn't receive frames within a timeout).

Another solution consists in caching the last I-frame and send it to the client - this can be taken into consideration.

**Comment by cothingsusr** [comment]
Thanks @aler9  for your response,
How can I add an  algorithm in the server that drops any P or B frame until an initial I-frame is sent?
Or how can I cache the last I-frame and send it to the client?

Thanks.

**Comment by aler9** [comment]
I've an update regarding this issue.

P and B frames can't be dropped from the stream even if they are useless. Clients must receive packets within a timeout, otherwise they close the connection to the server. If we stop sending P and B frames to clients, waiting for an I frame, this timeout is triggered, since it is generally about 2-3 secs, while the I frame interval is generally bigger.

Therefore, this feature can't be implemented. A client should silently discards P and B frames until it receives the first IDR.
