### ISSUE TITLE
ERR: server ports must be both zero or both not zero

### ISSUE THREAD

**Issue by eljefe80** [aler9/rtsp-simple-server#407]
## Which version are you using?

v0.16.2

## Which operating system are you using?

OS

- [ X ] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ X ] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

A follow-up to #396, which was successfully resolved, now the same ipcam gives the error in the title: 
> ERR: server ports must be both zero or both not zero

Which appears to be related to the transport declarations in the vlc dump:

> Transport: RTP/AVP/UDP;unicast;client_port=52764-52765;server_port=0-1;ssrc=4317f
> Transport: RTP/AVP/UDP;unicast;client_port=51546-51547;server_port=0-1;ssrc=70713f 

I'm attaching the same vlc packet dump from #396 for completeness
[vlc-ipcam-dump.txt](https://github.com/aler9/rtsp-simple-server/files/6566756/vlc-ipcam-dump.txt)

**Comment by aler9** [comment]
Hello, the problem is that your camera uses a RTSP version that doesn't provide the source port of the packets, and therefore the server can't validate incoming packets. Without this check, anyone would be allowed to send frames to the server and this is a security issue.

Anyway, since there are a couple of old cameras with this behavior, it's better to add a parameter inside the configuration file to allow a camera to use `server_port=0-1`, disabled by default, since it's a security issue.

**Comment by aler9** [comment]
an option `sourceAnyPortEnable` has been added to the configuration file; this will be available in the next release.

**Comment by eljefe80** [comment]
This works, thanks!

**Comment by aler9** [comment]
added in v0.16.3
