### ISSUE TITLE
ERR: unable to setup authentication: apexes not closed

### ISSUE THREAD

**Issue by a-backman** [aler9/rtsp-simple-server#420]
## Which version are you using?

v0.16.2

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Getting the following error when trying to connect to proxy source:
`2021/06/11 11:27:36 I [0/0] [path proxied] [rtsp source] ERR: unable to setup authentication: apexes not closed (realm="My RTSP Server)`

## Describe how to replicate the issue

Using this configuration:
```
proxied:
  source: rtsp://user:password@192.168.1.70/deviceStreams?deviceId=84d069fa-45b5-44f6-a88b-0a64450cda0e&source=1&nodeId=fb62caf2-0242-4f88-8b38-ce035d03b6d8
```

**Comment by aler9** [comment]
Hello, this can be fixed but you need to provide a dump of the data exchanged between the server and the camera, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by aler9** [comment]
This can't be solved without the author's help.
