### ISSUE TITLE
About Bandwidth Limitation

### ISSUE THREAD

**Issue by ROZ-MOFUMOFU-ME** [aler9/rtsp-simple-server#555]
It would be nice to be able to set the bandwidth limit on the stream sending side, as it is currently not configurable.

**Comment by aler9** [comment]
Hello, the problem of the bandwidth is that it depends on the stream that is being transmitted: the stream has to be re-encoded in order to change the bandwidth. Since the stream is generally not re-encoded during transmission, this can't be done.
This is different with respect to WebRTC implemented in browsers, where the stream is re-encoded and the encoder is tuned accordingly to the available bandwidth.
