### ISSUE TITLE
Problems when publishing more than 1 stream

### ISSUE THREAD

**Issue by Liroy2003** [aler9/rtsp-simple-server#56]
## Which version are you using?

v0.9.9 & v.0.9.8

## Describe the problem

When publishing more than 2 streams with ffmpeg the streams break down after about 20 secs. I tried different setups and double cheked my ffmpeg script. Then i tried v0.9.4 and there i have no problems. So it looks like a problem with the new versions.

**Comment by gustavobsch** [comment]
I second this! I've been testing all releases after 0.9.4 and I observe frequent disconnects.

**Comment by aler9** [comment]
Hello, this should be fixed in v0.9.10.
In v0.9.8 i introduced a hash map to rapidly find the owner of incoming packets, to improve performance; unfortunately i forgot to add the port to the map key, hence all clients with the same IP but different ports were put in the same slot.
Sorry for the regression.
@gustavobsch frequent disconnects are unrelated from this issue; if you still have problems please open a dedicated issue.
