### ISSUE TITLE
Question: UDP Socket/Buffer size

### ISSUE THREAD

**Issue by benbullnz** [aler9/rtsp-simple-server#57]
## Which version are you using?

v0.9.04

## Question:

I am trying to run a very low latency audio only server using opus encoded via ffmpeg. Publishing and subscription are both using UDP only. Are you able to provide any insights on the affects of UDP buffer read/write sizes in the go code and what affects raising or lowering this will/could have on latency? I remember you adjusting these in a version a few weeks ago and I think this may have caused my average latency to increase by 20ms or so. 

Ideally I would have a number of cloud vm's running to facilitate 1000's of audio only subscribers (split across a number of rtsp-simple-server instances) utilising the proxy functionality. 

I'm just interested in your thoughts on optimising UDP buffers/latency if I was to modify and compile the code myself.
Thanks

**Comment by aler9** [comment]
Hello, from what i know, changing the UDP buffer size in gortsplib shouldn't affect performance or latency:
* UDP packets are always sent with a size lower than the ethernet MTU (1500 bytes), otherwise fragmentation is quietly activated by the OS and performance decreases ([see here](https://serverfault.com/questions/246508/how-is-the-mtu-is-65535-in-udp-but-ethernet-does-not-allow-frame-size-more-than))
* UDP packets contain RTP frames; hence RTP frames are built by the publisher (ffmpeg) in a way not to exceed the (1500 bytes - UDP header) threshold
* RTP frames contain Opus frames; i don't know much about Opus, so i can't say if Opus frames are built with a size smaller than (1500 bytes - RTP header - UDP header), or if they are fragmented into multiple RTP frames

rtsp-simple-server buffer sizes are setup in this way:
* udp read buffer size = 2048 bytes (power of 2, greater than 1500)
* udp write buffer size = 128 * 1024 bytes
* tcp read buffer size = 128 * 1024 bytes
* tcp write buffer size = 128 * 1024 bytes

Why the 128k? because there are some badly-implemented clients like Larix that sends via TCP a lot of RTP frames in a single interleaved frame (i didn't mention it, but the interleaved frame is another layer that allows to send RTP packets via TCP, and can contain a lot of RTP frames), so it's a way to support these cases too.

Therefore, if you want to improve latency or bandwidth (the choice is between these two) i'd try to tune the codec parameters.s
