### ISSUE TITLE
Delay and missed packet ffmpeg errors when streaming via UDP with player on same system

### ISSUE THREAD

**Issue by smallnetbuilder** [aler9/rtsp-simple-server#58]
## Which version are you using?

v0.9.4

## Describe the problem

I'm investigating smearing when playing UDP streams. Publishing using this command:
 `ffmpeg  -re -stream_loop -1 -i jellyfish-10-mbps-hd-h264.mkv -c copy -f rtsp rtsp://localhost:8556/stream`
When running mpv player using --rtsp-transport=udp on the same system,  so no network involved, player continuously issues messages like these:
```
[ffmpeg/demuxer] rtsp: max delay reached. need to consume packet
[ffmpeg/demuxer] rtsp: RTP: missed 27 packets
```
and displays smearing and blockiness.
If I play the file with --rtsp-transport=tcp, there are no messages and video plays fine. But player shows this message on startup:
```
Using hardware decoding (vaapi).
VO: [opengl] 1920x1080 vaapi[nv12]
```
I've tried running the 5 Mbps version of the jellyfish file and get the same problem.

Q1: Why is hardware decoding used when transport is TCP? Is this the explanation for no smearing with TCP?
Q2: I read question 57 suggesting adjusting ffmpeg codec, but not sure how to proceed. Can you advise?

**Comment by aler9** [comment]
Hello, i was able to replicate the problem with the exact details you posted.

Unfortunately i think the problem lays in mpv's ffmpeg backend, and in the way mpv interfaces with ffmpeg; i tried with other RTSP servers, and in every case after a while the message `max delay reached. need to consume packet` starts to appear; for instance, by using the VLC RTSP integrated server:
```
cvlc -vvv jellyfish-10-mbps-hd-h264.mkv --sout '#rtp{sdp=rtsp://:5000/}'
```

and mpv:
```
mpv --rtsp-transport=udp rtsp://127.0.0.1:5000/
```

I don't know the exact behavior of mpv, but it seems that it uses ffmpeg in a wrong way while dealing with RTSP and UDP:
* it allows delay to be accumulated
* it allows seeking, that can't be done with live streams and is indeed blocked by VLC

These problems also happens with TCP, but frames are not dropped and seeking has the effect of freezing the player instead of crashing it. In my opinion the mpv team is aware of the situation, and that's the reason why TCP is the default protocol.

I can't answer to Q1, it's a mpv question. All i can say is that rtsp-simple-server routes the same exact frames with both UDP and TCP, it doesn't even touch them.
Regarding Q2, RTSP is usually able to stream any kind of H264, but players have an initial delay due to the fact that they must wait for an I-Frame, so if you want to improve the situation, you can re-encode the video and set a low i-frame interval (https://stackoverflow.com/questions/30979714/how-to-change-keyframe-interval-in-ffmpeg).

**Comment by smallnetbuilder** [comment]
Thanks for looking at this Alessandro. I suspected it was something in ffmpeg and/or mpv. Closing this.
