### ISSUE TITLE
sourceProtocol do not work

### ISSUE THREAD

**Issue by zhaibin18** [aler9/rtsp-simple-server#582]
## Which version are you using?

 v0.17.3

## Which operating system are you using?

OS

- [*] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [*] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

config file:

paths:
  test1:
    source: rtsp://239.3.1.182:8001
    sourceOnDemand: yes
    sourceProtocol: _**udp**_

## Describe how to replicate the issue

logs:

2021/09/23 15:32:55 I [0/0] rtsp-simple-server v0.17.3
2021/09/23 15:32:55 I [0/0] [path test1] created
2021/09/23 15:32:55 I [0/0] [path test1] [rtsp source] started
2021/09/23 15:32:55 D [0/0] [path test1] [rtsp source] connecting
2021/09/23 15:32:55 I [0/0] [path test1] [rtsp source] ERR: dial tcp 239.3.1.182:8001: connect: network is unreachable
2021/09/23 15:32:55 I [0/0] [RTSP] UDP/RTP listener opened on :8000
2021/09/23 15:32:55 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
2021/09/23 15:32:55 I [0/0] [RTSP] TCP listener opened on :8554
2021/09/23 15:32:55 I [0/0] [RTMP] listener opened on :1935
2021/09/23 15:32:55 I [0/0] [HLS] listener opened on :8888
2021/09/23 15:33:00 D [0/0] [path test1] [rtsp source] connecting
2021/09/23 15:33:00 I [0/0] [path test1] [rtsp source] ERR: dial _**tcp**_ 239.3.1.182:8001: connect: network is unreachable
2021/09/23 15:33:05 D [0/0] [path test1] [rtsp source] connecting
2021/09/23 15:33:05 I [0/0] [path test1] [rtsp source] ERR: dial _**tcp**_ 239.3.1.182:8001: connect: network is unreachable
2021/09/23 15:33:10 D [0/0] [path test1] [rtsp source] connecting
2021/09/23 15:33:10 I [0/0] [path test1] [rtsp source] ERR: dial _**tcp**_ 239.3.1.182:8001: connect: network is unreachable

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, in my opinion you're trying to read a RTP stream instead of a RTSP stream, and this is not supported.
A RTP stream also needs a `.sdp` file that contains the track list and the codec of each track.
RTSP performs this operation automatically during the handshake, and then makes a RTP stream available to the client.

In my opinion you can use `ffmpeg` to read the `RTP` stream, by using an `.sdp` file, and then send this stream to the server with `RTSP`; the command like could be this (but i'm not sure):

```
ffmpeg -re -i mysdp.sdp -c copy -f rtsp rtsp://localhost:8554/mystream
```

**Comment by zhaibin18** [comment]
OK, get it, thanks!
