### ISSUE TITLE
API: path - use default from paths:all for undefined parameters?

### ISSUE THREAD

**Issue by gluedots** [aler9/rtsp-simple-server#586]
Setting a single parameter for a path via API works great, but it seems to use the system default for all the undefined parameters instead of using the parameters defined in paths:all.

For example, if I set **paths:all:readUser** and **paths:special_path:runOnPublish**, _special_path_ will trigger the **runOnPublish** command as desired but will ignore the **readUser** parameter from paths:all while _another_path_ will use the **readUser** as desired.

Could we get a way set a particular parameter to use whatever is set in paths:all? Maybe we could set a parameter to NULL if we want that parameter to use whatever is defined in paths:all.

Or have a way to modify the default value for undefined values via api or even environment.

Thanks!

**Comment by aler9** [comment]
This behavior is intended, as it reflects the one already in use for parsing the configuration file. For instance, given this configuration:

```yml
paths:
  all:
    readUser: myuser
    readPass: mypass

  path1:
    publishUser: myuser
    publishPass: mypass
```

`readUser` and `readPass` won't be inherited by `path1`. 

This is caused by the fact that `all` is an alias for the regexp `.*`, that means "any path".

This is also caused by the fact that at the moment there isn't an hierarchical configuration system - there's only one level, and path configurations can't inherit values from another configuration.

At the moment i can't think a better solution, therefore, to solve your issue you have two choices:

* create path configs that use regular expressions (i.e. `~^(path1|path2)$`): this config will be applied to both `path1` and `path2`
* use a wrapper around the API that fills the missing parameters.
