### ISSUE TITLE
Question: Server specs recommendations 

### ISSUE THREAD

**Issue by joaquin03** [aler9/rtsp-simple-server#62]
Hi grate project!

In my case, I have 200 cameras inside a firewall, and many users that want to consume the video, for small 
periods (10s - 30s) but at the worst hours could be 30 - 50 different consumers at the same time. The video is small (640 x 360 - 6ftp)

1) Is possible with "On-demand publishing" do this?

2) With server specs do you recomend, for this use case?

Thanks!!

**Comment by aler9** [comment]
Hello, at the moment sources are opened and closed with two different criteria:
* when sourceOnDemand is off, sources are kept always opened - this is ideal for small bursts, for instance, i use the server in a project in which a series of ffmpeg instances connect to the server every 30 seconds to generate JPEG images, and then disconnect - i never got any problem
* when sourceOnDemand is on, sources are closed immediately when there are no clients. This allows to save bandwidth, but is not ideal for clients that connect and disconnect ofter, since the server has to connect to the sources many times.

Therefore, an interesting enhancement could be the introduction of a parameter `sourceDisconnectAfterSeconds`, that tells the server to close the connection to a source only if there are no clients and a certain period has passed.

Regarding server specs, it's impossible to tell for certain, since performance depends on
* source size and encoding (the source size is not enough to determine performance)
* number of publishers
* number of clients

I generally use a script to stress the test, something like this (publish something in /stream and change 40 with the number of readers you want to use):
```sh
#!/bin/sh -e

trap 'kill $(ps -o pid= --ppid $$)' INT

for i in $(seq 1 40); do
    ffmpeg -i rtsp://localhost:8554/stream -c copy -f mp4 -y /dev/null &
done

wait
```

and i measure CPU usage.

**Comment by aler9** [comment]
new parameters have been added to better control the "on demand" feature (v0.12.0)
