### ISSUE TITLE
After API post server not store changes

### ISSUE THREAD

**Issue by mxkacsa** [aler9/rtsp-simple-server#633]
## Which version are you using?

v0.17.6

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

After changing config with API endpoints and restart the server, every change has gone.

## Describe how to replicate the issue

1. enable API in config
2. start the server
3. change something with API or add new paths
4. restart the server

result: config file not changed, old config loaded

**Comment by aler9** [comment]
At the moment the server API is stateless and doesn't save any change to disk. This was done since saving these changes to the configuration file would be a problem since

* contiuously writing to a file is slow (a DB would be ideal)
* YAML comments and general formatting (spaces, additional newlines, key ordering) of the configuration file would be dropped during updates

At the moment i can't think about a better solution (sorry!).

If you want to implement retention, you can save paths, users, etc in a DB of your own, and apply this state when the server starts through API.
