### ISSUE TITLE
Question: Why can't use slashes on the path?

### ISSUE THREAD

**Issue by pelemarse** [aler9/rtsp-simple-server#66]
## Which version are you using?

  v0.9.11

## Describe the problem

Up to and including version 0.9.7, everything worked normally, but from the next version 0.9.8, it is no longer possible to use slashes on paths.

It is a great pity that such a solution has been chosen. Maybe there’s still a chance to leave slashes on the path?

example: **/slashes/on/the/path/is/super/feature**

**Comment by aler9** [comment]
Hello, slashes have been temporarily disabled because they interfered with the stream setup mechanism.

Each track in a stream has a unique path, for instance `rtsp://host/path/streamID=1`, formed by the stream path, i.e. `rtsp://host/path`, and a prefix, i.e. `/streamID=1`. 
Slashes in the path url messed up the function responsible for extracting the stream path from the track path.

But they'll be readded soon.

**Comment by aler9** [comment]
added in v0.9.12
