### ISSUE TITLE
API v1/stats endpoint

### ISSUE THREAD

**Issue by tompointexe** [aler9/rtsp-simple-server#676]
Hi, little feature i would like to have in the api

## Describe the feature

It would be a simple json page that spits out the endpoint name and have a number under it saying the number of active sesion watching that specific endoint
idealy it would work with the web viewers, as the  v1/paths/list only give 1 time the HLSMuxer for x person watching on web

Thanks a lot

**Comment by aler9** [comment]
Hello,

> idealy it would work with the web viewers, as the v1/paths/list only give 1 time the HLSMuxer for x person watching on web

it's not technically possible to get a viewer count with HLS, since it doesn't work with sessions (that are able to uniquely identify users) but works with a web server that serves segments, and allows everyone to download them. Nonetheless, you can implement such mechanism in your app through cookies or websockets.

> It would be a simple json page that spits out the endpoint name and have a number under it saying the number of active sesion watching that specific endoint

The HTTP API already provides the list of all the viewers of a certain path.

**Comment by tompointexe** [comment]
Okey !! i'l look more depely in the web api :) thanks
