### ISSUE TITLE
ANNOUNCE validation now rejects h.264 tracks that do not provide `sprop-parameter-sets` in the SDP

### ISSUE THREAD

**Issue by tmatth** [aler9/rtsp-simple-server#715]
## Which version are you using?

v0.17.10

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

Since https://github.com/aler9/rtsp-simple-server/commit/f7ea9a6b2d2eedb7f6bd3f63ee98cebc169e0f25 rtsp-simple-server rejects `ANNOUNCE`d h.264 tracks that don't include `sprop-parameter-sets` in its SDP, which excludes any source who is signalling sps+pps inband.

I saw this similar exception being added but it's on the source end:
https://github.com/aler9/rtsp-simple-server/commit/c7b2ae83df8fb6f87154b719d519480aa9bf6d73

## Describe how to replicate the issue

Use an RTSP upstream that doesn't include `sprop-parameter-sets` in its SDP, e.g.
```
time="30-11-2021 21:49:39.064" level=info msg="   Media: &{video 0 RTP/AVP 96 <nil> <nil> [] <nil> [rtpmap:96 H264/90000 fmtp:96 profile-level-id=42e01f;packetization-mode=1 control:trackID=0 sendonly]}"
```

**Comment by aler9** [comment]
Hello, the server supports proxing streams that don't provide SPS/PPS (and fixes them, since c7b2ae8), but i was not aware of any RTSP client that pushes H264 tracks without SPS / PPS. That check was added exactly to discover any client with this behavior.

What is the name and version of the client?

**Comment by tmatth** [comment]
It is just a custom client which can relay arbitrary rtsp streams which we wrote using gortsplib, I will try to provide a simplified version that demonstrates the behaviour.

**Comment by aler9** [comment]
It's better not to support this special case in order to avoid problems. You can copy and paste the code in [rtsp_source.go](https://github.com/aler9/rtsp-simple-server/blob/main/internal/core/rtsp_source.go) in order to add SPS and PPS to streams that don't have them. In the future this feature will be integrated directly into gortsplib's Client.

**Comment by tmatth** [comment]
> It's better not to support this special case in order to avoid problems. In the future the server will become smarter and smarter and H264 params are absolutely needed. You can copy and paste the code in [rtsp_source.go](https://github.com/aler9/rtsp-simple-server/blob/main/internal/core/rtsp_source.go) in order to add SPS and PPS to streams that don't have them. In the future this feature will be integrated directly into gortsplib's Client.

Thanks for the suggestion, because the existing `handleMissingH264Params` has a lot of `internal` dependencies it's not really practical to use outside of `rtsp-simple-server`, but once it's integrated in gortsplib this would be a good option.
