### ISSUE TITLE
Support more chars in the path name

### ISSUE THREAD

**Issue by dorintt** [aler9/rtsp-simple-server#74]
## Which version are you using?

v0.9.12

## Enhancement request

`ERR: invalid path name: can contain only alfanumeric characters, underscore, minus or slash`

Why can't `?` or `&` be supported as well?

**Comment by aler9** [comment]
Hello, `?` and `&` are part of the query part of an url, not of the path:
```
rtsp://user:pass@domain:port/path?param1=1&param2=2
```

During SETUP, the track id is added to the RTSP url, in order to form a track URL:
 ```
rtsp://user:pass@domain:port/path/trackID=1
```
This can't be done if the path contains `?` and `&`.

Furthermore, some clients would certainly mark as invalid the url.

If you're asking to support parameters, it _maybe_ could be done, but they surely can't be added to the `path` field.

**Comment by dorintt** [comment]
Well yes I know they are part of the query, but wasn't sure how it could be handled. That is my problem actually, that some 3rd party system automatically add query parameters and therefore can't get access to this server.

**Comment by aler9** [comment]
Ok, now i understand and i think this needs to be fixed.

**Comment by aler9** [comment]
Query parameters can now be added when publishing or reading; they have no influence on the path.
This is implemented in master and will be added to the next release.

**Comment by aler9** [comment]
added in v0.9.13
