### ISSUE TITLE
ERR: invalid transport header: invalid ports

### ISSUE THREAD

**Issue by emolatur** [aler9/rtsp-simple-server#762]
Hi. Could you either remove whatever limit this is encountering, or document how to do so?

I have a Victure PC730. It's a piece of garbage but it works with vlc, mplayer, ffplay, shinobi, zoneminder, and onvif device manager (at least to view the stream). Your simple server, being used as a proxy, is giving me:

2021/12/31 15:30:40 I [0/8] [path victure01] [rtsp source] ERR: invalid transport header: invalid ports (40000-40001,ssrc=FFFFCCCC)

The way I am reading this, the camera is saying "sure, fetch the stream on ports 40000 or 40001" and your program is saying "Nope, I don't like 40000 or 40001." Well I need your program to like it, because the camera is made in China and has no documentation or support whatsoever, so changing the camera's behavior is not an option.

I've stared at the .yml file hoping to find some configurable acceptable range of ports. None found.

**Comment by aler9** [comment]
Hello, the problem is simply that the server is unable to parse the transport header sent by the camera to the server, probably because the camera uses a non standard transport header format. There are no limitations on the ports or whatsoever. Please reopen the issue by following [instructions](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=), that clearly explain how to produce the network dump needed in order to fix the issue.
