### ISSUE TITLE
invalid SDP: failed to decode

### ISSUE THREAD

**Issue by Johnny421** [aler9/rtsp-simple-server#8]
I downloaded this IOS app : https://apps.apple.com/us/app/larix-broadcaster/id1042474385
so i can test rtsp-simple-server. But the server output this when i push from the app:

```
2020/05/13 17:25:55 [RTSP client 192.168.1.4:63659] connected
2020/05/13 17:25:55 [RTSP client 192.168.1.4:63659] OPTIONS
2020/05/13 17:25:56 [RTSP client 192.168.1.4:63659] ANNOUNCE
2020/05/13 17:25:56 [RTSP client 192.168.1.4:63659] ERR: invalid SDP: failed to decode message: DecodeError in section s: origin address not set
2020/05/13 17:25:56 [RTSP client 192.168.1.4:63659] disconnected
```

The same app is working fine with Wowza Streaming Engine using RTSP.

**Comment by aler9** [comment]
Hi, thanks for the report, this should be fixed in v0.6.1. let me know if it worked.

**Comment by Johnny421** [comment]
Thank you it works now!

Can you stream/push through TCP instead of UDP?  

I thought TCP was only part of RTSP to control RTP, but the stream packets is sent through UDP. 

I'm asking this because i was able to playback the stream through TCP and UDP.

and the server output this: "publishing on path 'mystream', 2 tracks via tcp ". When pushing from the app.

Can you please confirm  the above ?

**Comment by Johnny421** [comment]
> Hi, thanks for the report, this should be fixed in v0.6.1. let me know if it worked.

Thank you it works now!

Can you stream/push through TCP instead of UDP?

I thought TCP was only part of RTSP to control RTP, but the stream packets is sent through UDP.

I'm asking this because i was able to playback the stream through TCP and UDP.

and the server output this: "publishing on path 'mystream', 2 tracks via tcp ". When pushing from the app.

Can you please confirm the above ?

**Comment by Johnny421** [comment]
> Hi, thanks for the report, this should be fixed in v0.6.1. let me know if it worked.

Thank you it works now!

Can you stream/push through TCP instead of UDP?

I thought TCP was only part of RTSP to control RTP, but the stream packets is sent through UDP.

I'm asking this because i was able to playback the stream through TCP and UDP.

and the server output this: "publishing on path 'mystream', 2 tracks via tcp ". When pushing from the app.

Can you please confirm the above ?

**Comment by aler9** [comment]
Hi, an RTSP session is composed by two different parts:
- the negotiation, in which the streaming protocol is chosen. This happens exclusively via TCP
- the streaming, this can happen in TCP or UDP, on the basis of the negotiation.

Streaming via TCP is better when there's a firewall in the middle, but is less efficient, and packets can be buffered, causing a delay.
Streaming via UDP is the ideal situation, since is more efficient and packets cannot get buffered, as they're discarded in case of connection errors.

You can chose the protocol by either tuning the client (i.e. in VLC there's the flag --rtsp-tcp) or the server (in rtsp-simple-proxy you can use --protocols=udp).

**Comment by BandwidthMedia** [comment]
Hi Alessandro,

I we have successfully tested the server, however I have a comment back
from one of our developers who looked into this issue:

"About the query, yes, just want to check if they can add multiple PLAY
support, since it's allowed in rtsp protocol."

 Is this something which is possible to include in the server and perhaps
ignore any subsequent play requests  after the first?
We have tested many IP cameras and other rtsp servers and have not run into
this issue before is all.

Best Regards

Chris
