### ISSUE TITLE
Cannot kick FFmpeg clients

### ISSUE THREAD

**Issue by Curid** [aler9/rtsp-simple-server#800]
## Which version are you using?

v0.17.14

## FFmpeg version

Latest

## Which operating system are you using?

- [x] Linux amd64 `go run`

## Describe the issue

FFmpeg clients stay connected after being kicked via `v1/rtspsessions/kick/{id}`

## Describe how to replicate the issue

Producer:
```
ffmpeg -loglevel debug -re -stream_loop -1 -i video.mp4 -c:v libx264 -f rtsp rtsp://127.0.0.1:8554/test
```

Reader:
```
ffmpeg -loglevel debug -i rtsp://127.0.0.1:8554/test -f null -
```

Both clients stay connected after being kicked and continue to listen until server stops.

**Comment by aler9** [comment]
Hello, this is not a bug. Both the publisher and the reader are kicked from the server indeed, they aren't publishing or reading the stream and there isn't any open connection between them and the server.

The problem is that FFmpeg, when the UDP transport protocol is used, closes the TCP connection with the server, and can't receive any signal from the server, apart from RTP and RTCP packets. The FFmpeg that is publishing is still sending packets (that are not processed by the server) and the FFmpeg that is reading is still listening for packets (that are not sent to it).

If you think that this behavior is a bug and that FFmpeg should keep an open TCP connection in order to listen for messages from the server, open an issue on the FFmpeg bug tracking system.

**Comment by Curid** [comment]
@aler9 Sorry, I thought port 8554 only accepted TCP streams.
Specifying `-rtsp_transport tcp` solves it.
