### ISSUE TITLE
Session id is generated in response to ANNOUNCE instead of SETUP requests 

### ISSUE THREAD

**Issue by tom1235465** [aler9/rtsp-simple-server#840]
## Which version are you using?

v0.17.16

## Which operating system are you using?

- [x] Linux arm7 standard
- [x] Windows amd64 standard

## Describe the issue

Session identifier is generated in response to ANNOUNCE requests (and is expected in SETUP requests?).

Regarding RFC2326 and RFC7826, it should be generated in response to the SETUP requests:

[https://datatracker.ietf.org/doc/html/rfc2326#page-33](url):

> The server generates session identifiers in response to SETUP requests.

[https://datatracker.ietf.org/doc/html/rfc7826#section-2.2](url):

> When receiving a SETUP request, the server determines if the media resource is available and if one or more of the of the transport parameter specifications are acceptable.  If that is successful, an RTSP session context is created and the relevant parameters and state is stored.  An identifier is created for the RTSP session and included in the response in the Session header

[https://datatracker.ietf.org/doc/html/rfc7826#section-18.49](url):
>    An RTSP session is created by the server as a result of a successful SETUP request, and in the response, the session identifier is given to the client.

I had a problem (#822) with an IP camera that sends the session id not at the SETUP request, but at the following requests. We found a workaround for the moment, but if it is not too complicated to change one day, that would be nice.

Thanks again for sharing your hard work with us
Tom

**Comment by aler9** [comment]
Hello, thanks for sharing this info, sometimes protocol misinterpretations are found and corrected whenever possible.

The problem here is that sessions are used to uniquely identify RTSP publishers and readers, since these can disconnect and reconnect to the server, and connections are not enough for the purpose. Furthermore, client status (is publishing / is reading, what is reading, etc) is associated to the session, not in the client, for the same reason. I still believe that sessions are the best place to save client data, independently from the fact that a client has issued a SETUP request.

In my opinion the best way to solve this issue is hiding the session header from ANNOUNCE responses, without touching anything else.

**Comment by tom1235465** [comment]
I'm not sure if I understood the problem of #822 correct, but I think as the camera doesn't send the session id at the setup request, the server started again the function newServerSession and with the new session id the former info of the announcement got lost. Does that sound plausible? If that's the case, then hiding isn't enough.  
I'm fine with our workaround, I just want to mention it in case someone else runs into the same problem.

**Comment by aler9** [comment]
> as the camera doesn't send the session id at the setup request, the server started again the function newServerSession and with the new session id the former info of the announcement got lost

There are two possible approaches:

* scraping the hidden session idea, saving ANNOUNCE data into the connection and creating a session only during SETUP
* adding a "session" field to the connection, using it to save the current session (that is created during ANNOUNCE) and read it during SETUP requests. A client is not intended to interact with multiple sessions, so this is fine. 

I'm sharing my thoughts before doing anything since this is a sensitive issue, and any change must not cause problems elsewhere.

**Comment by tom1235465** [comment]
Both ideas sound good to me

**Comment by aler9** [comment]
It's stick with the second approach, that consists in creating a session during ANNOUNCE (but not sending its id through the response), since in this way the server is allowed to check if a stream can be created or not during ANNOUNCE.

Furthermore, a connection doesn't have a "state" field, therefore a connection would be free to send multiple ANNOUNCE requests without any check. A session, contrarily,  has a "state" field that allows to check if a client is trying to send multiple ANNOUNCE requests or invalid requests.

**Comment by tom1235465** [comment]
Thank you for the very fast fix, I can confirm that the latest commit fixed my problem :-)

After SETUP, the camera puts a PLAY request which gets answerd by a Bad Request "...(must be in state [prePlay play], while is in state preRecord)" But as this is another problem I first try to find out if it is a server or camera bug. I can use it by changing the cases Play and Record. I'll open another issue when I have more info.

Thanks again, your server fits perfect for my project. I didn't find something comparable (except Wowza Streaming Engine for 175 Euro montly, which is not an option).

**Comment by tom1235465** [comment]
Sorry, it only works if thers no basic auth. 
With activated auth I get:
```
2022/02/19 21:31:21 INF [RTSP] listener opened on :8554 (TCP)
2022/02/19 21:31:21 INF [HLS] listener opened on :8888
2022/02/19 21:31:21 INF [API] listener opened on stream.fritz.box:9997
2022/02/19 21:31:37 INF [RTSP] [conn 192.168.1.128:4953] opened
2022/02/19 21:31:37 DEB [RTSP] [conn 192.168.1.128:4953] [c->s] ANNOUNCE rtsp://stream.fritz.box:8554/live/123456 RTSP/1.0
CSeq: 1
Content-Length: 399
Content-Type: application/sdp

v=0
o=- 86902271 86902271 IN IP4 127.0.0.1
s=
i=
c=IN IP4 192.168.1.153
t=0 0
a=x-qt-text-nam:
a=x-qt-text-inf:
a=x-qt-text-cmt:source application:Whee
a=x-qt-text-aut:
a=x-qt-text-cpy:
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=42801E;sprop-parameter-sets=J0KAHtoCgPTAVSAAAAMAIAAAB4wIACSeAAkn173wvCIRqA==,KM48gA==
a=control:trackID=1

2022/02/19 21:31:37 INF [RTSP] [session 867990231] opened by 192.168.1.128:4953
2022/02/19 21:31:37 DEB [RTSP] [session 867990231] non-critical authentication error: 
2022/02/19 21:31:37 DEB [RTSP] [conn 192.168.1.128:4953] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 1
Server: gortsplib
WWW-Authenticate: Basic realm="IPCAM"


2022/02/19 21:31:37 DEB [RTSP] [conn 192.168.1.128:4953] [c->s] ANNOUNCE rtsp://stream.fritz.box:8554/live/123456 RTSP/1.0
Authorization: Basic c3RyZWFtZXI6ZHJlYW1lcg==
CSeq: 2
Content-Length: 399
Content-Type: application/sdp

v=0
o=- 86902271 86902271 IN IP4 127.0.0.1
s=
i=
c=IN IP4 192.168.1.153
t=0 0
a=x-qt-text-nam:
a=x-qt-text-inf:
a=x-qt-text-cmt:source application:Whee
a=x-qt-text-aut:
a=x-qt-text-cpy:
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=42801E;sprop-parameter-sets=J0KAHtoCgPTAVSAAAAMAIAAAB4wIACSeAAkn173wvCIRqA==,KM48gA==
a=control:trackID=1

2022/02/19 21:31:37 DEB [RTSP] [conn 192.168.1.128:4953] [s->c] RTSP/1.0 400 Bad Request
CSeq: 2
Server: gortsplib


2022/02/19 21:31:37 INF [RTSP] [conn 192.168.1.128:4953] closed (connection is linked to another session)
2022/02/19 21:31:37 INF [RTSP] [session 867990231] closed (not in use)
```
I think the session must be closed right away after

> 2022/02/19 21:31:37 DEB [RTSP] [conn 192.168.1.128:4953] [s->c] RTSP/1.0 401 Unauthorized

or at least before the next ANNOUNCE

**Comment by tom1235465** [comment]
Thanks, I'd say it is fixed

**Comment by aler9** [comment]
added in v0.18.0
