### ISSUE TITLE
address family not supported by protocol family on macos

### ISSUE THREAD

**Issue by Caskia** [aler9/rtsp-simple-server#895]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
Run rstp-simple-server on my macos as server, when client uses vlcmulticast to connect, it failed. Server logs show address family not supported by protocol family.  Is multicast support on macos? I have tried on my windows, it's running correctly. Hope to get your feedback, thank you.

## Did you attach the server logs?

[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/8322945/rtsp-simple-server.log)

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Thanks for reporting this issue, it has been fixed in the main branch and will be fixed in the next release. In the meanwhile, you can use this nightly release for testing:
[rtsp-simple-server_v0.18.0-11-g91ce2dd_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8530708/rtsp-simple-server_v0.18.0-11-g91ce2dd_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8530711/rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8530713/rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_armv7.tar.gz)
[rtsp-simple-server_v0.18.0-11-g91ce2dd_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8530715/rtsp-simple-server_v0.18.0-11-g91ce2dd_windows_amd64.zip)
[rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8530718/rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_armv6.tar.gz)
[rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8530719/rtsp-simple-server_v0.18.0-11-g91ce2dd_linux_amd64.tar.gz)

**Comment by aler9** [comment]
added in v0.18.1.
