### ISSUE TITLE
ERR: expected 'RTSP/1.0', got

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#916]
## Which version are you using?

v0.18.0

## Which operating system are you using?

- [x] Windows amd64 standard

## Describe the issue

Testing an RTSP camera and getting this error in logs:

```
2022/04/12 23:09:05 INF [path channel2] [rtsp source] ERR: expected 'RTSP/1.0', got [222 208 143 112 77 226 122 4 207 168 16 244 119 31 35 129 176 10 112 244 203 60 100 14 205 199 16 158 25 8 104 148 242 191 241]
2022/04/12 23:09:11 INF [path channel2] [rtsp source] ready
2022/04/12 23:09:15 INF [path channel2] [rtsp source] ERR: expected 'RTSP/1.0', got [46 69 131]
2022/04/12 23:09:20 INF [path channel2] [rtsp source] ready
2022/04/12 23:09:24 INF [path channel2] [rtsp source] ERR: expected 'RTSP/1.0', got [196 87 107 15 65 213 85 130 238 53 245 39 10 62 223 127 72 211 7 139 57 44 132 55 226 52 183 53 168 140 212 164 58 7 111 38 155 69 94 126 109 202 128 203 126 112 12 143 194 149 122 150 58 120 251 172 239 166 46 11 18 214 163 3 253 148 27 25 87 97 145 210 192 229 35 26 175 164 7 208 231 31 253 230 90 3 78 12 36 34 4 70 153 9 203 162 192 106 51 84 73 101 5 97 146 197 205 251 218 235 250 254 75 189 231 100 187 95 101 58 208 6 63 255 128 250 28 228 247 188 163 145 154 163 26 73 218 187 33 150 129 93 151 213 118 208 153 247]
2022/04/12 23:09:29 INF [path channel2] [rtsp source] ready
2022/04/12 23:09:34 INF [path channel2] [rtsp source] ERR: expected 'RTSP/1.0', got [52 60 89 217 31 50 59 127 46 255 107 149 242 97 247 110 119 182 216 5 247 24 98 71 74 156 165 48 39 218 247 38 161 202 67 114 142 147 154 56 225 108 45 53 125 240 85 76 159 41 166 251 89 210 129 161 24 36 214 16 166 238 140 10 205 183 30 184 77 58 105 36 247 83 242 251 88 176 115 90 4 143 202 112 107 55 118 178 157 163 13 44 128 204 149 219 120 182 222 61 45 76 168 128 57 138 210 247 112 203 179 37 226 215 82 154 135 112 50 180 27 180 233 53 144 94 43 18 223 70 84 172 106 191 244 250 149 76 27 72 31 182 235 113 236 126 225 251 198 94 6 67 18 75 133 140]
```

as well as

`2022/04/12 23:16:21 INF [path channel2] [rtsp source] ERR: buffer length exceeds 255`

## Describe how to replicate the issue

1. start the server
2. publish with direct link to the rtsp camera
3. read with vlc or ffplay

**Comment by aler9** [comment]
Hello, sorry but your camera isn't speaking RTSP. Maybe it's RTSPS, maybe it's another protocol. Anyway it's replying to a RTSP request with junk.

**Comment by zengqingfa** [comment]
I had a similar problem, when my proxy server added 9 streams, 5 streams would break frequently (about once every 8 or 9 seconds, and then reconnect), with a similar error, not when only 6 streams were added.

![图片](https://user-images.githubusercontent.com/39977054/172282873-13d8d2ca-ac0f-4551-9837-6b76b4a4ab04.png)

The version I use is [v0.17.17](https://github.com/aler9/rtsp-simple-server/releases/tag/v0.17.17),but I don't use the latest version because the `readBufferSize` parameter has been removed from later versions and some streams that support `H265` will not play.

**Comment by zengqingfa** [comment]
I had a similar problem, when my proxy server added 9 streams, 5 streams would break frequently (about once every 8 or 9 seconds, and then reconnect), with a similar error, not when only 6 streams were added.

![图片](https://user-images.githubusercontent.com/39977054/172282873-13d8d2ca-ac0f-4551-9837-6b76b4a4ab04.png)

The version I use is [v0.17.17](https://github.com/aler9/rtsp-simple-server/releases/tag/v0.17.17),but I don't use the latest version because the `readBufferSize` parameter has been removed from later versions and some streams that support `H265` will not play.

**Comment by sureone** [comment]
Anyone have the solution for this problem, I got the same issue for hikvision Camera.

**Comment by aler9** [comment]
@sureone please open another issue and follow instructions in order to provide details that allow to replicate (server logs, network dumps, etc).
