### ISSUE TITLE
 tcp :8888: bind: address already in use

### ISSUE THREAD

**Issue by yufeiluo** [aler9/rtsp-simple-server#939]
```
./rtsp-simple-server
2022/05/06 18:13:12 INF rtsp-simple-server v0.18.2
2022/05/06 18:13:12 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/05/06 18:13:12 INF [RTMP] listener opened on :1935
2022/05/06 18:13:12 ERR listen tcp :8888: bind: address already in use
2022/05/06 18:13:12 INF [RTSP] listener is closing
2022/05/06 18:13:12 INF [RTMP] listener is closing
2022/05/06 18:13:12 INF waiting for external commands
```

Check with lsof:

`lsof -i:8888`

Nothing as output!

Which process is using the port:8888 then?

**Comment by aler9** [comment]
1) use the [issue template](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=) otherwise the issue will be inevitably closed as in this case
2) that error is returned by the OS, therefore there is surely something listening on `:8888`; use `sudo lsof -i -P -n | grep LISTEN` to find out what is it.
