### ISSUE TITLE
ll-hls get "muxer error: wrong nal_ref_idc"

### ISSUE THREAD

**Issue by Classsic** [aler9/rtsp-simple-server#966]
I'm trying to publish from ffmpeg qsv, with this command:
` ffmpeg -stimeout 30000000 -rtsp_transport tcp  -hwaccel qsv -c:v h264_qsv -i rtsp://192.168.0.180/live -an  -c:v h264_qsv  -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:18554/test`
and get this error:
`2022/06/02 20:16:32 INF [HLS] [muxer proxied] is converting into HLS
2022/06/02 20:16:34 INF [HLS] [muxer proxied] destroyed (muxer error: wrong nal_ref_idc)`
With normal rtsp camera stream work fine (about 3s of delay).
I'm trying to reduce this with hw encoding.
Any clue that´s is wrong?
BTW, cheers for llhls support!

**Comment by aler9** [comment]
Thanks for reporting this issue, this error happens when the server tries to parse the SPS of your stream. Actually the server checks that the nal_ref_idc field of a SPS NALU is equal to 3, otherwise it throws an error.

I've read again the H264 specification (ISO 14496-10:2020) and it says that nal_ref_idc of a SPS must be != 0, not equal to 3.

**Comment by aler9** [comment]
Please try this nightly release and let me know if it works
[rtsp-simple-server_v0.19.0-14-g758b9d5_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8835618/rtsp-simple-server_v0.19.0-14-g758b9d5_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.19.0-14-g758b9d5_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8835619/rtsp-simple-server_v0.19.0-14-g758b9d5_linux_amd64.tar.gz)
[rtsp-simple-server_v0.19.0-14-g758b9d5_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8835620/rtsp-simple-server_v0.19.0-14-g758b9d5_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.19.0-14-g758b9d5_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8835621/rtsp-simple-server_v0.19.0-14-g758b9d5_linux_armv6.tar.gz)
[rtsp-simple-server_v0.19.0-14-g758b9d5_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8835622/rtsp-simple-server_v0.19.0-14-g758b9d5_linux_armv7.tar.gz)
[rtsp-simple-server_v0.19.0-14-g758b9d5_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8835623/rtsp-simple-server_v0.19.0-14-g758b9d5_windows_amd64.zip)

**Comment by Classsic** [comment]
Now works perfect!
I want to reduce the latency closest to 1s, but can´t get any under 2.5 o 3s.
What can I try apart of readme recomendation (already change the iframe to 0.5s).
Thanks.

**Comment by aler9** [comment]
If you want to decrease latency you have to decrease hlsPartDuration.

Latency won't go below hlsPartDuration * 4 (1 part is being generated, the other 3 are queued by the browser).

Since the minimum value of hlsPartDuration is the duration of a videoSample, if you have a 30fps video, then the minimum latency is

33ms * 4 = 133 ms

Of course this is theoretical and the latency will be greater, but anyway this is the limit of the protocol.
