### ISSUE TITLE
When nine cameras are added, five or six cameras are frequently disconnected and then reconnected

### ISSUE THREAD

**Issue by zengqingfa** [aler9/rtsp-simple-server#973]
## Which version are you using?

[v0.17.17](https://github.com/aler9/rtsp-simple-server/releases/tag/v0.17.17)

ps: I don't use the latest version because the readBufferSize parameter has been removed from later versions and some streams that support H265 will not play.

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue
When my proxy server added 9 streams, 5 streams would break frequently (about once every 8 or 9 seconds, and then reconnect), with a similar error, not when only 6 streams were added.

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

![图片](https://user-images.githubusercontent.com/39977054/172286274-7a798f3a-cfc1-4844-844d-038bfd79b063.png)
yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, please open another issue about the H265 problem - nobody wanted to remove H265 support, i was not aware of the fact that there are H265 sources that use non-standard RTP packet sizes, and i don't have a non-standard H264 track.

Regarding this issue, it's impossible to understand whether it's still standing or it has been fixed, since you're not using the latest version.
