### ISSUE TITLE
LLHLS - seek issue

### ISSUE THREAD

**Issue by EvgIL74** [aler9/rtsp-simple-server#999]
Hi, 
I tried to use llhls and its working very good in real-time (latency around 5 sec)  until i tried to seek back in hls.js player.
I put  hlsSegmentCount: 20000. It didn't work properly and got spinning circle. I tried multiply time and its same phenomena. 
Is some limit with seek ?

**Comment by mpisat** [comment]
yml file has a configuration for it.
# Number of HLS segments to keep on the server.
# Segments allow to seek through the stream.
# Their number doesn't influence latency.
hlsSegmentCount: 7

maybe increase it to your needs?

**Comment by EvgIL74** [comment]
Look at the previous post where I changed hlsSegmentCount to 20000 in the yml file. It's looking like the exe file grows up compared to hlsSegmentCount = 7, but it doesn't help the seek procedure.

**Comment by EvgIL74** [comment]
Look at the previous post where I changed hlsSegmentCount to 20000 in the yml file. It's looking like the exe file grows up compared to hlsSegmentCount = 7, but it doesn't help the seek procedure.

**Comment by EvgIL74** [comment]
> yml file has a configuration for it.
> 
> # Number of HLS segments to keep on the server.
> # Segments allow to seek through the stream.
> # Their number doesn't influence latency.
> hlsSegmentCount: 7
> 
> maybe increase it to your needs?

Look at the previous post where I changed hlsSegmentCount to 20000 in the yml file. It's looking like the exe file grows up compared to hlsSegmentCount = 7, but it doesn't help the seek procedure.

**Comment by mpisat** [comment]
hls.js has limits in configuration, you may need a bigger buffer back to rewind.
https://github.com/video-dev/hls.js/blob/master/docs/API.md

**Comment by EvgIL74** [comment]
I found something suspicious with #EXT-X-GAP when I defined hlsSegmentCount to 20000. 
HLS file includes  #EXT-X-GAP - 20000 times and first segment is seg20000.mp4. 

#EXT-X-GAP
#EXTINF:1.00000,
gap.mp4
#EXTINF:1.00000,
seg20000.mp4
#EXTINF:1.00000,
seg20001.mp4

In this case HLS player calculates 5 hours stream duration when I started stream few seconds ago.

**Comment by aler9** [comment]
Hello, at the moment gaps are inserted in place of segments when the number of generated segments is less than hlsSegmentCount. This is because tests showed that  LL-HLS works well on iOS only when segments are at least 7. Therefore, gaps are needed in order to react at least 7 segments.

But i understand that this behavior is not optimal in case someone is interested into seeking, as gaps mess up the duration.

A new behavior could consist into adding at maximum 6 gaps, even when hlsSegmentCount is much greater than 7. This new behavior needs to be tested with iOS in order to check compatibility.

**Comment by aler9** [comment]
Now the server creates only 7 gaps instead of a number of gaps equal to `hlsSegmentCount`. This means that this issue is fixed.

**Comment by aler9** [comment]
added in v0.19.3
